WindowsFormsApp1::Database
Database WindowsFormsApp1.Database._instance
Singleton сущность базы данных, с которой на данный момент работает программа.
Referenced by WindowsFormsApp1.Database.GetInstance, WindowsFormsApp1.Database.LoadInstance, WindowsFormsApp1.Database.GetNewInstance.
HashMap<int, Client> WindowsFormsApp1.Database._clients
Хэш-таблица клиентов, находящихся в базе данных. Принцип разрешения коллизий: открытая адресация (метод двойного хэширования).
Referenced by WindowsFormsApp1.Database.Database, WindowsFormsApp1.Database.AddClient, WindowsFormsApp1.Database.RemoveClient, WindowsFormsApp1.Database.FindClient, WindowsFormsApp1.Database.ClientSize, WindowsFormsApp1.Database.ClientArray, WindowsFormsApp1.Database.ClientsFunction, WindowsFormsApp1.Database.Consistence.
HashMap<int, Machine> WindowsFormsApp1.Database._machines
Хэш-таблица банкоматов, находящихся в базе данных. Принцип разрешения коллизий: метод цепочек. Хэш функция: остаток от деления.
Referenced by WindowsFormsApp1.Database.Database, WindowsFormsApp1.Database.AddMachine, WindowsFormsApp1.Database.RemoveMachine, WindowsFormsApp1.Database.FindMachine, WindowsFormsApp1.Database.MachineSize, WindowsFormsApp1.Database.MachineArray, WindowsFormsApp1.Database.MachinesFunction, WindowsFormsApp1.Database.Consistence.
Tree<Operation> WindowsFormsApp1.Database._operations
Бинарное дерево операций, находящихся в базе данных.
Referenced by WindowsFormsApp1.Database.Database, WindowsFormsApp1.Database.AddOperation, WindowsFormsApp1.Database.RemoveOperation, WindowsFormsApp1.Database.FindOperation, WindowsFormsApp1.Database.OperationSize, WindowsFormsApp1.Database.OperationArray, WindowsFormsApp1.Database.Consistence, WindowsFormsApp1.Database.ClientOperationReport, WindowsFormsApp1.Database.MachineOperationReport, WindowsFormsApp1.Database.MachinePercentReport.
Tree<Percent> WindowsFormsApp1.Database._percents
Бинарное дерево процентов, находящихся в базе данных.
Referenced by WindowsFormsApp1.Database.Database, WindowsFormsApp1.Database.AddPercent, WindowsFormsApp1.Database.RemovePercent, WindowsFormsApp1.Database.FindPercent, WindowsFormsApp1.Database.PercentSize, WindowsFormsApp1.Database.PercentArray, WindowsFormsApp1.Database.Consistence, WindowsFormsApp1.Database.OperationPercentReport, WindowsFormsApp1.Database.MachinePercentReport.
static Database WindowsFormsApp1.Database.GetInstance()
Функция, предоставляющая доступ к синглтон базе данных. При необходимости создает пустую базу данных и возвращает ее.
База данных, с которой на данный момент работает программа.
References WindowsFormsApp1.Database._instance, WindowsFormsApp1.Database.Database.
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.OperationsOfClient.ClientsKey_CellClick, WindowsFormsApp1.PercentsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.OperationsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfOperation.OperationsKey_CellClick, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click, WindowsFormsApp1.GUI.сохранитьToolStripMenuItem_Click.
static Result WindowsFormsApp1.Database.LoadInstance(string filePath)
При корректности данных в файле, загружает базу данных из него и делает ее рабочей базой данных.
filePath Путь к файлу базы данных. Результат загрузки базы данных.
References WindowsFormsApp1.Database._instance, WindowsFormsApp1.Checks.CheckClient, WindowsFormsApp1.Checks.CheckMachine, WindowsFormsApp1.Checks.CheckOperation, WindowsFormsApp1.Checks.CheckPercent, WindowsFormsApp1.Database.Database, WindowsFormsApp1.Result.Success.
Referenced by WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
static Database WindowsFormsApp1.Database.GetNewInstance()
Заменяет рабочую базу данных на новую.
Пустая база данных.
References WindowsFormsApp1.Database._instance, WindowsFormsApp1.Database.Database.
Referenced by WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
WindowsFormsApp1.Database.Database()
Приватный конструктор, используемый для создания пустой базы данных. Инициализирует все структуры данных пустыми.
References WindowsFormsApp1.Database._clients, WindowsFormsApp1.Database._machines, WindowsFormsApp1.Database._operations, WindowsFormsApp1.Database._percents.
Referenced by WindowsFormsApp1.Database.GetInstance, WindowsFormsApp1.Database.GetNewInstance, WindowsFormsApp1.Database.LoadInstance.
Result WindowsFormsApp1.Database.Save(string filePath)
Сохраняет базу данных на жесткий диск.
filePath Путь к файлу, в который будет производится сохранение. Результат сохранения базы данных.
References WindowsFormsApp1.Machine.Address, WindowsFormsApp1.Client.BankName, WindowsFormsApp1.Machine.BankName, WindowsFormsApp1.Client.CardNumber, WindowsFormsApp1.Operation.CardNumber, WindowsFormsApp1.Database.ClientArray, WindowsFormsApp1.Database.ClientSize, WindowsFormsApp1.Database.MachineArray, WindowsFormsApp1.Machine.MachineNumber, WindowsFormsApp1.Operation.MachineNumber, WindowsFormsApp1.Database.MachineSize, WindowsFormsApp1.Client.Name, WindowsFormsApp1.Database.OperationArray, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Percent.OperationName, WindowsFormsApp1.Database.OperationSize, WindowsFormsApp1.Percent.Percent1, WindowsFormsApp1.Database.PercentArray, WindowsFormsApp1.Database.PercentSize, WindowsFormsApp1.Percent.ReceiverBank, WindowsFormsApp1.Percent.SenderBank, WindowsFormsApp1.Operation.Sum.
Referenced by WindowsFormsApp1.GUI.сохранитьToolStripMenuItem_Click.
Result WindowsFormsApp1.Database.AddClient(Client client)
Добавляет клиента в базу данных, если это не нарушает целостность базы данных.
client Клиент для добавления. Сообщение об успешном добавлении или о проблеме целостности.
References WindowsFormsApp1.Database._clients, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button3_Click.
Result WindowsFormsApp1.Database.AddMachine(Machine machine)
Добавляет банкомат в базу данных, если это не нарушает целостность базы данных.
machine Банкомат для добавления. Сообщение об успешном добавлении или о проблеме целостности.
References WindowsFormsApp1.Database._machines, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button1_Click.
Result WindowsFormsApp1.Database.AddOperation(Operation operation)
Добавляет операцию в базу данных, если это не нарушает целостность базы данных.
operation Операция для добавления. Сообщение об успешном добавлении или о проблеме целостности.
References WindowsFormsApp1.Database._operations, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button4_Click.
Result WindowsFormsApp1.Database.AddPercent(Percent percent)
Добавляет процент в базу данных, если это не нарушает целостность базы данных.
percent Процент для добавления. Сообщение об успешном добавлении или о проблеме целостности.
References WindowsFormsApp1.Database._percents, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button2_Click.
Result WindowsFormsApp1.Database.RemoveClient(Client client)
Удаляет клиента из базы данных, если это не нарушает целостность базы данных.
client Клиент для удаления. Сообщение об успешном удалении или о проблеме целостности.
References WindowsFormsApp1.Database._clients, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button6_Click.
Result WindowsFormsApp1.Database.RemoveMachine(Machine machine)
Удаляет банкомат из базы данных, если это не нарушает целостность базы данных.
machine Банкомат для удаления. Сообщение об успешном удалении или о проблеме целостности.
References WindowsFormsApp1.Database._machines, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button5_Click.
Result WindowsFormsApp1.Database.RemoveOperation(Operation operation)
Удаляет операцию из базы данных, если это не нарушает целостность базы данных.
operation Операция для удаления. Сообщение об успешном удалении или о проблеме целостности.
References WindowsFormsApp1.Database._operations, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button8_Click.
Result WindowsFormsApp1.Database.RemovePercent(Percent percent)
Удаляет процент из базы данных, если это не нарушает целостность базы данных.
percent Процент для удаления. Сообщение об успешном удалении или о проблеме целостности.
References WindowsFormsApp1.Database._percents, WindowsFormsApp1.Database.Consistence.
Referenced by WindowsFormsApp1.GUI.button7_Click.
SearchQuery<Client> WindowsFormsApp1.Database.FindClient(Client client)
Производит поиск в базе данных клиента, соответствующего входным данным.
client Клиент, соответствия которому необходимо найти. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database._clients.
Referenced by WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.Database.FindClient.
SearchQuery<Machine> WindowsFormsApp1.Database.FindMachine(Machine machine)
Производит поиск в базе данных банкомата, соответствующего входным данным.
machine Банкомат, соответствия которому необходимо найти. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database._machines.
Referenced by WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.Database.FindMachine.
SearchQuery<Operation> WindowsFormsApp1.Database.FindOperation(Operation operation)
Производит поиск в базе данных операции, соответствующей входным данным.
operation Операция, соответствия которой необходимо найти. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database._operations.
Referenced by WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.Database.FindOperation.
SearchQuery<Percent> WindowsFormsApp1.Database.FindPercent(Percent percent)
Производит поиск в базе данных процента, соответствующего входным данным.
percent Процент, соответствия которому необходимо найти. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database._percents.
Referenced by WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.Database.FindPercent.
SearchQuery<Client> WindowsFormsApp1.Database.FindClient(int cardNumber)
Производит поиск в базе данных банкомата, соответствующего входным данным.
cardNumber Номер карты искомого клиента. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database.FindClient.
SearchQuery<Machine> WindowsFormsApp1.Database.FindMachine(int machineNumber)
Производит поиск в базе данных банкомата, соответствующего входным данным.
machineNumber Номер банкомата, соответствия которому необходимо найти. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database.FindMachine.
SearchQuery<Operation> WindowsFormsApp1.Database.FindOperation(string operationName, int cardNumber, int machineNumber)
Производит поиск в базе данных операции, соответствующей входным данным.
operationName Название операции. cardNumber Номер карты, с которой произведена операция. machineNumber Номер банкомата, на котором произведена операция. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database.FindOperation.
SearchQuery<Percent> WindowsFormsApp1.Database.FindPercent(string operationName, string senderBank, string receiverBank)
Производит поиск в базе данных процента, соответствующего входным данным.
operationName Название операции. senderBank Название банка отправителя. receiverBank Название банка получателя. Результат запроса поиска, содержащий информацию о количестве сравнений и совпадение, если таковое найдено.
References WindowsFormsApp1.Database.FindPercent.
int WindowsFormsApp1.Database.ClientSize()
Возвращает количество клиентов.
Количество клиентов.
References WindowsFormsApp1.Database._clients.
Referenced by WindowsFormsApp1.Database.Save.
int WindowsFormsApp1.Database.MachineSize()
Возвращает количество банкоматов.
Количество банкоматов.
References WindowsFormsApp1.Database._machines.
Referenced by WindowsFormsApp1.Database.Save.
int WindowsFormsApp1.Database.OperationSize()
Возвращает количество операций.
Количество операций.
References WindowsFormsApp1.Database._operations.
Referenced by WindowsFormsApp1.Database.Save.
int WindowsFormsApp1.Database.PercentSize()
Возвращает количество процентов.
Количество процентов.
References WindowsFormsApp1.Database._percents.
Referenced by WindowsFormsApp1.Database.Save.
Client [] WindowsFormsApp1.Database.ClientArray()
Возвращает массив клиентов, доступных в базе данных.
Массив клиентов.
References WindowsFormsApp1.Database._clients.
Referenced by WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.Database.Save, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
Machine [] WindowsFormsApp1.Database.MachineArray()
Возвращает массив банкоматов, доступных в базе данных.
Массив банкоматов.
References WindowsFormsApp1.Database._machines.
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.Database.Save, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
Operation [] WindowsFormsApp1.Database.OperationArray()
Возвращает массив операций, доступных в базе данных.
Массив операций.
References WindowsFormsApp1.Database._operations.
Referenced by WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.Database.Save, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
Percent [] WindowsFormsApp1.Database.PercentArray()
Возвращает массив процентов, доступных в базе данных.
Массив процентов.
References WindowsFormsApp1.Database._percents.
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.Database.Save, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
HashFunction<int> WindowsFormsApp1.Database.ClientsFunction()
Возвращает хэш-функцию, используемую для таблицы клиентов данной базы данных.
Хэш-функция клиентов.
References WindowsFormsApp1.Database._clients.
Referenced by WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
HashFunction<int> WindowsFormsApp1.Database.MachinesFunction()
Возвращает хэш-функцию, используемую для таблицы машин данной базы данных.
Хэш-функция машин.
References WindowsFormsApp1.Database._machines.
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
Result WindowsFormsApp1.Database.Consistence()
Производит проверку базы данных на целостность.
Сообщение о причине нарушения целостности или отсутствия таковых.
References WindowsFormsApp1.Database._clients, WindowsFormsApp1.Database._machines, WindowsFormsApp1.Database._operations, WindowsFormsApp1.Database._percents, WindowsFormsApp1.Client.CardNumber, WindowsFormsApp1.Operation.CardNumber, WindowsFormsApp1.Machine.MachineNumber, WindowsFormsApp1.Operation.MachineNumber, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Percent.OperationName.
Referenced by WindowsFormsApp1.Database.AddClient, WindowsFormsApp1.Database.AddMachine, WindowsFormsApp1.Database.AddOperation, WindowsFormsApp1.Database.AddPercent, WindowsFormsApp1.Database.RemoveClient, WindowsFormsApp1.Database.RemoveMachine, WindowsFormsApp1.Database.RemoveOperation, WindowsFormsApp1.Database.RemovePercent.
Report<Client, Operation> WindowsFormsApp1.Database.ClientOperationReport(Client client)
Создает отчет об операциях, проведенных клиентом.
client Клиент, операции которого попадут в отчет. Отчет об операциях этого клиента, содержащий их количество и конкретные операции.
References WindowsFormsApp1.Database._operations, WindowsFormsApp1.Report< K, V >.Add, WindowsFormsApp1.Client.CardNumber, WindowsFormsApp1.Operation.CardNumber.
Referenced by WindowsFormsApp1.OperationsOfClient.ClientsKey_CellClick, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click.
Report<Machine, Operation> WindowsFormsApp1.Database.MachineOperationReport(Machine machine)
Создает отчет об операциях, проведенных этим банкоматом.
machine Банкомат, операции которого попадут в отчет. Отчет об операциях этого банкомата, содержащий их количество и конкретные операции.
References WindowsFormsApp1.Database._operations, WindowsFormsApp1.Report< K, V >.Add, WindowsFormsApp1.Machine.MachineNumber, WindowsFormsApp1.Operation.MachineNumber.
Referenced by WindowsFormsApp1.OperationsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click.
Report<Operation, Percent> WindowsFormsApp1.Database.OperationPercentReport(Operation operation)
Создает отчет о процентах по указанному типу операций.
operation Операция, проценты по которой попадут в отчет. Отчет о процентах этой операции, содержащий их количество и конкретные операции.
References WindowsFormsApp1.Database._percents, WindowsFormsApp1.Report< K, V >.Add, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Percent.OperationName.
Referenced by WindowsFormsApp1.PercentsOfOperation.OperationsKey_CellClick, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click.
Report<Machine, Percent> WindowsFormsApp1.Database.MachinePercentReport(Machine machine)
Создает отчет о процентах по операциям, проведенных этим банкоматом.
machine Банкомат, проценты по операциям которого попадут в отчет. Отчет о процентах по операциям этого банкомата, содержащий их количество и конкретные операции.
References WindowsFormsApp1.Database._operations, WindowsFormsApp1.Database._percents, WindowsFormsApp1.Report< K, V >.Add, WindowsFormsApp1.Machine.BankName, WindowsFormsApp1.Machine.MachineNumber, WindowsFormsApp1.Operation.MachineNumber, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Percent.OperationName, WindowsFormsApp1.Percent.ReceiverBank.
Referenced by WindowsFormsApp1.PercentsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click.