WinFormsApp1::Tree
Position<T> WinFormsApp1.Tree< T >._root
Корень дерева.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::ToArray, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Add, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Remove, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Find.
int WinFormsApp1.Tree< T >._size
Размер дерева.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::ToArray, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Size, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Add, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Remove.
T [] WinFormsApp1.Tree< T >.ToArray()
Преобразует коллекцию в массив элементов.
Массив элементов.
int WinFormsApp1.Tree< T >.Size()
Возвращает размер коллекции.
Размер коллекции.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::ToArray.
void WinFormsApp1.Tree< T >.Add(T element)
Добавляет элемент в коллекцию.
element Добавляемый элемент.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Add.
bool WinFormsApp1.Tree< T >.Remove(T element)
Удаляет элемент из коллекии.
element Удаляемый элемент. Возвращает true, если элемент найден и удален, иначе false.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Remove.
void WinFormsApp1.Tree< T >.Find(SearchQuery< T > query)
Поиск указанного в запросе элемента, по указанному индексу хранилища, учитывая стратегии разрешения коллизий.
query Поисковый запрос, содержащий искомый объект.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Find.
int WinFormsApp1.Tree< T >.FillArray(T[] arr, int index, Position< T > pos)
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::FillArray, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::ToArray.
void WinFormsApp1.Tree< T >.Add(Position< T > parent, T element)
Внутренний рекурсивный метод, для добавления элемента.
parent Родительская ячейка. element Добавляемый элемент.
bool WinFormsApp1.Tree< T >.Remove(Position< T > position, T element)
Внутренний рекурсивный метод, для удаления элемента.
position Ячейка для проверки. element Удаляемый элемент.
Position<T> WinFormsApp1.Tree< T >.Max(Position< T > parent)
Ищет максимальный элемент дерева, начинающегося с указанной позиции.
parent Корневой элемент дерева. в котором ведется поиск. Максимальный элемент в дереве.
Referenced by WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Max, WinFormsApp1.Tree< WindowsFormsApp1.Operation >::Remove.
void WinFormsApp1.Tree< T >.Find(Position< T > position, SearchQuery< T > query)
Внутренний рекурсивный метод, для поиска элемента.
position Ячейка для проверки. query Поисковый запрос.