.TH "Client.cs" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApp1\&.Client\fP"
.br
.RI "Класс, описывающий клиента банковской системы\&. Обладает ключом типа int\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApp1\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
