.TH "Database.cs" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Database.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApp1\&.Database\fP"
.br
.RI "Класс-оболочка базы данных, предоставляющий доступ ко всем методам, необходимым для работы со структурами данных\&. Реализует шаблон проектирования Singleton\&. Предоставляет возможности для сохранения и загрузки базы данных на жесткий диск, при помощи сериализации\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApp1\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
