.TH "ListStorage.cs" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListStorage.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWinFormsApp1\&.ListStorage< K, V >\fP"
.br
.ti -1c
.RI "class \fBWinFormsApp1\&.ListStorage< K, V >\&.Position< T >\fP"
.br
.RI "Структура, представляющая собой элемент односвязного списка, используемая для разрешения коллизий в \fBListStorage\fP\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWinFormsApp1\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
