.TH "operationFound.cs" 3 "Вс 28 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operationFound.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApp1\&.operationFound\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApp1\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
