.TH "RB.cs" 3 "Вс 28 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RB.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApp1\&.RB< T >\fP"
.br
.ti -1c
.RI "class \fBWindowsFormsApp1\&.RB< T >\&.Node< T >\fP"
.br
.RI "Object of type \fBNode\fP contains 4 properties Colour Left Right Parent Data "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApp1\fP"
.br
.in -1c
.SS "Перечисления"

.in +1c
.ti -1c
.RI "enum \fBColor\fP "
.br
.in -1c
.SH "Перечисления"
.PP 
.SS "enum \fBColor\fP\fC [strong]\fP"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
