.TH "Report.cs" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Report.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApp1\&.Report< K, V >\fP"
.br
.RI "Отчет о данных, соответствующих запросу\&. Ищет все данные, соответсвующие запросу и сортирует их используя \fBISorter\fP\&. "
.ti -1c
.RI "class \fBWindowsFormsApp1\&.Report< K, V >\&.Container< T >\fP"
.br
.RI "Котейнер, являющийся первым элементом списка и предоставляющий методы работы со списком\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApp1\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
