.TH "Tree.cs" 3 "Вс 28 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tree.cs
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBWinFormsApp1\&.Tree< T >\fP"
.br
.RI "Коллекция вида бинарное дерево\&. "
.ti -1c
.RI "class \fBWinFormsApp1\&.Tree< T >\&.Position< T >\fP"
.br
.RI "Вершина дерева, реализующий методы работы с поддервом\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBWinFormsApp1\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
