.TH "WindowsFormsApp1.GUI" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.GUI
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Form\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBGUI\fP ()"
.br
.in -1c
.SS "Статические открытые данные"

.in +1c
.ti -1c
.RI "static bool \fBstopflag\fP = false"
.br
.ti -1c
.RI "static \fBDatabase\fP \fBmyDatabase\fP = \fBDatabase\&.GetNewInstance\fP()"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Освободить все используемые ресурсы\&. "
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBbutton1_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton3_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton2_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton4_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBdataGridView1_CellClick\fP (object sender, DataGridViewCellEventArgs e)"
.br
.ti -1c
.RI "void \fBbutton5_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton6_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton7_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbutton8_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBdataGridView3_CellClick\fP (object sender, DataGridViewCellEventArgs e)"
.br
.ti -1c
.RI "void \fBdataGridView2_CellClick\fP (object sender, DataGridViewCellEventArgs e)"
.br
.ti -1c
.RI "void \fBdataGridView4_CellClick\fP (object sender, DataGridViewCellEventArgs e)"
.br
.ti -1c
.RI "void \fBbutton9_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBcomboBox1_SelectedIndexChanged\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBоперацииПоКлиентуToolStripMenuItem_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBоперацииБанкоматаToolStripMenuItem_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBпроцентыОперацийToolStripMenuItem_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBпроцентыБанкоматаToolStripMenuItem_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBсохранитьToolStripMenuItem_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBимпортироватьToolStripMenuItem_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBсоздатьToolStripMenuItem1_Click\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "Required method for Designer support - do not modify the contents of this method with the code editor\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "int \fBNumRows1\fP = \-1"
.br
.ti -1c
.RI "int \fBNumRows2\fP = \-1"
.br
.ti -1c
.RI "int \fBNumRows3\fP = \-1"
.br
.ti -1c
.RI "int \fBNumRows4\fP = \-1"
.br
.ti -1c
.RI "int \fBindex1\fP = \-1"
.br
.ti -1c
.RI "int \fBindex2\fP = \-1"
.br
.ti -1c
.RI "int \fBindex3\fP = \-1"
.br
.ti -1c
.RI "int \fBindex4\fP = \-1"
.br
.ti -1c
.RI "string \fBstate\fP = ''"
.br
.ti -1c
.RI "System\&.ComponentModel\&.IContainer \fBcomponents\fP = null"
.br
.RI "Обязательная переменная конструктора\&. "
.ti -1c
.RI "System\&.Windows\&.Forms\&.MenuStrip \fBmenuStrip1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBсоздатьToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBимпортироватьToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBсохранитьToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridView \fBdataGridView1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel2\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel3\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel4\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridView \fBdataGridView2\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridView \fBdataGridView3\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridView \fBdataGridView4\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton2\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton3\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton4\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton5\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton6\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton7\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton8\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBотчётыToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBоперацииПоКлиентуToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBоперацииБанкоматаToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBпроцентыОперацийToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBпроцентыБанкоматаToolStripMenuItem\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Label \fBlabel5\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.Button \fBbutton9\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ToolStripMenuItem \fBсоздатьToolStripMenuItem1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBHash\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBНомер\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBАдрес\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBНазваниеБанка\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBHash1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBНомерКарточки\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBБанк\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBФИО\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBТип\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBОтправитель\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBПолучатель\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBПроцент\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBТипОперации1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBНомерКарточки1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBНомерБанкомата\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn \fBСуммаОперации\fP"
.br
.ti -1c
.RI "\fBWindowsFormsApp1\&.WaterMarkTextBox\fP \fBwaterMarkTextBox1\fP"
.br
.ti -1c
.RI "System\&.Windows\&.Forms\&.ComboBox \fBcomboBox1\fP"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "WindowsFormsApp1\&.GUI\&.GUI ()"

.SH "Методы"
.PP 
.SS "void WindowsFormsApp1\&.GUI\&.button1_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button2_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button3_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button4_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button5_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button6_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button7_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button8_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.button9_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.comboBox1_SelectedIndexChanged (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.dataGridView1_CellClick (object sender, DataGridViewCellEventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.dataGridView2_CellClick (object sender, DataGridViewCellEventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.dataGridView3_CellClick (object sender, DataGridViewCellEventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.dataGridView4_CellClick (object sender, DataGridViewCellEventArgs e)\fC [private]\fP"

.SS "override void WindowsFormsApp1\&.GUI\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Освободить все используемые ресурсы\&. 
.PP
\fBАргументы\fP
.RS 4
\fIdisposing\fP истинно, если управляемый ресурс должен быть удален; иначе ложно\&.
.RE
.PP

.SS "void WindowsFormsApp1\&.GUI\&.InitializeComponent ()\fC [private]\fP"

.PP
Required method for Designer support - do not modify the contents of this method with the code editor\&. 
.SS "void WindowsFormsApp1\&.GUI\&.импортироватьToolStripMenuItem_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.операцииБанкоматаToolStripMenuItem_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.операцииПоКлиентуToolStripMenuItem_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.процентыБанкоматаToolStripMenuItem_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.процентыОперацийToolStripMenuItem_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.создатьToolStripMenuItem1_Click (object sender, EventArgs e)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.GUI\&.сохранитьToolStripMenuItem_Click (object sender, EventArgs e)\fC [private]\fP"

.SH "Данные класса"
.PP 
.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button2\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button3\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button4\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button5\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button6\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button7\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button8\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Button WindowsFormsApp1\&.GUI\&.button9\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ComboBox WindowsFormsApp1\&.GUI\&.comboBox1\fC [private]\fP"

.SS "System\&.ComponentModel\&.IContainer WindowsFormsApp1\&.GUI\&.components = null\fC [private]\fP"

.PP
Обязательная переменная конструктора\&. 
.SS "System\&.Windows\&.Forms\&.DataGridView WindowsFormsApp1\&.GUI\&.dataGridView1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridView WindowsFormsApp1\&.GUI\&.dataGridView2\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridView WindowsFormsApp1\&.GUI\&.dataGridView3\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridView WindowsFormsApp1\&.GUI\&.dataGridView4\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Hash\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Hash1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.index1 = \-1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.index2 = \-1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.index3 = \-1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.index4 = \-1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Label WindowsFormsApp1\&.GUI\&.label1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Label WindowsFormsApp1\&.GUI\&.label2\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Label WindowsFormsApp1\&.GUI\&.label3\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Label WindowsFormsApp1\&.GUI\&.label4\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.Label WindowsFormsApp1\&.GUI\&.label5\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.MenuStrip WindowsFormsApp1\&.GUI\&.menuStrip1\fC [private]\fP"

.SS "\fBDatabase\fP WindowsFormsApp1\&.GUI\&.myDatabase = \fBDatabase\&.GetNewInstance\fP()\fC [static]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.NumRows1 = \-1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.NumRows2 = \-1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.NumRows3 = \-1\fC [private]\fP"

.SS "int WindowsFormsApp1\&.GUI\&.NumRows4 = \-1\fC [private]\fP"

.SS "string WindowsFormsApp1\&.GUI\&.state = ''\fC [private]\fP"

.SS "bool WindowsFormsApp1\&.GUI\&.stopflag = false\fC [static]\fP"

.SS "\fBWindowsFormsApp1\&.WaterMarkTextBox\fP WindowsFormsApp1\&.GUI\&.waterMarkTextBox1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Адрес\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Банк\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.НазваниеБанка\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Номер\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.НомерБанкомата\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.НомерКарточки\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.НомерКарточки1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Отправитель\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Получатель\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Процент\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.СуммаОперации\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.Тип\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.ТипОперации1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.DataGridViewTextBoxColumn WindowsFormsApp1\&.GUI\&.ФИО\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.импортироватьToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.операцииБанкоматаToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.операцииПоКлиентуToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.отчётыToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.процентыБанкоматаToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.процентыОперацийToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.создатьToolStripMenuItem\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.создатьToolStripMenuItem1\fC [private]\fP"

.SS "System\&.Windows\&.Forms\&.ToolStripMenuItem WindowsFormsApp1\&.GUI\&.сохранитьToolStripMenuItem\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
