.TH "WindowsFormsApp1.WaterMarkTextBox" 3 "Вс 28 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.WaterMarkTextBox
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:TextBox\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBWaterMarkTextBox\fP ()"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "override void \fBOnCreateControl\fP ()"
.br
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs args)"
.br
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "\fBColor\fP \fBWaterMarkColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBWaterMarkText\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBJoinEvents\fP (Boolean join)"
.br
.ti -1c
.RI "void \fBWaterMark_Toggel\fP (object sender, EventArgs args)"
.br
.ti -1c
.RI "void \fBEnableWaterMark\fP ()"
.br
.ti -1c
.RI "void \fBDisbaleWaterMark\fP ()"
.br
.ti -1c
.RI "void \fBWaterMark_FontChanged\fP (object sender, EventArgs args)"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "Font \fBoldFont\fP = null"
.br
.ti -1c
.RI "Boolean \fBwaterMarkTextEnabled\fP = false"
.br
.ti -1c
.RI "\fBColor\fP \fB_waterMarkColor\fP = Color\&.Gray"
.br
.ti -1c
.RI "string \fB_waterMarkText\fP = 'Water Mark'"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "WindowsFormsApp1\&.WaterMarkTextBox\&.WaterMarkTextBox ()"

.SH "Методы"
.PP 
.SS "void WindowsFormsApp1\&.WaterMarkTextBox\&.DisbaleWaterMark ()\fC [private]\fP"

.SS "void WindowsFormsApp1\&.WaterMarkTextBox\&.EnableWaterMark ()\fC [private]\fP"

.SS "void WindowsFormsApp1\&.WaterMarkTextBox\&.JoinEvents (Boolean join)\fC [private]\fP"

.SS "override void WindowsFormsApp1\&.WaterMarkTextBox\&.OnCreateControl ()\fC [protected]\fP"

.SS "override void WindowsFormsApp1\&.WaterMarkTextBox\&.OnPaint (PaintEventArgs args)\fC [protected]\fP"

.SS "void WindowsFormsApp1\&.WaterMarkTextBox\&.WaterMark_FontChanged (object sender, EventArgs args)\fC [private]\fP"

.SS "void WindowsFormsApp1\&.WaterMarkTextBox\&.WaterMark_Toggel (object sender, EventArgs args)\fC [private]\fP"

.SH "Данные класса"
.PP 
.SS "\fBColor\fP WindowsFormsApp1\&.WaterMarkTextBox\&._waterMarkColor = Color\&.Gray\fC [private]\fP"

.SS "string WindowsFormsApp1\&.WaterMarkTextBox\&._waterMarkText = 'Water Mark'\fC [private]\fP"

.SS "Font WindowsFormsApp1\&.WaterMarkTextBox\&.oldFont = null\fC [private]\fP"

.SS "Boolean WindowsFormsApp1\&.WaterMarkTextBox\&.waterMarkTextEnabled = false\fC [private]\fP"

.SH "Полный список свойств"
.PP 
.SS "\fBColor\fP WindowsFormsApp1\&.WaterMarkTextBox\&.WaterMarkColor\fC [get]\fP, \fC [set]\fP"

.SS "string WindowsFormsApp1\&.WaterMarkTextBox\&.WaterMarkText\fC [get]\fP, \fC [set]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
