.TH "WindowsFormsApp1.Checks" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.Checks
.SH SYNOPSIS
.br
.PP
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static bool \fBCheckMachine\fP (string number, string address, string name)"
.br
.ti -1c
.RI "static bool \fBCheckClient\fP (string number, string bank, string name)"
.br
.ti -1c
.RI "static bool \fBCheckPercent\fP (string name, string sender, string receiver, string percent)"
.br
.ti -1c
.RI "static bool \fBCheckOperation\fP (string name, string number, string bank, string sum)"
.br
.in -1c
.SH "Методы"
.PP 
.SS "static bool WindowsFormsApp1\&.Checks\&.CheckClient (string number, string bank, string name)\fC [static]\fP"

.SS "static bool WindowsFormsApp1\&.Checks\&.CheckMachine (string number, string address, string name)\fC [static]\fP"

.SS "static bool WindowsFormsApp1\&.Checks\&.CheckOperation (string name, string number, string bank, string sum)\fC [static]\fP"

.SS "static bool WindowsFormsApp1\&.Checks\&.CheckPercent (string name, string sender, string receiver, string percent)\fC [static]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
