.TH "WindowsFormsApp1.Client" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.Client \- Класс, описывающий клиента банковской системы\&. Обладает ключом типа int\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBWinFormsApp1\&.IKeyedElement< int >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBClient\fP (int cardNumber, string bankName, string name)"
.br
.RI "Основной конструктор для создания клиента\&. "
.ti -1c
.RI "int \fBGetKey\fP ()"
.br
.ti -1c
.RI "int \fBCompare\fP (\fBIElement\fP elem)"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBCardNumber\fP => \fB_cardNumber\fP"
.br
.RI "Публичный геттер для номера карты\&. "
.ti -1c
.RI "string \fBBankName\fP => \fB_bankName\fP"
.br
.RI "Публичный геттер для названия обслуживающего банка\&. "
.ti -1c
.RI "string \fBName\fP => \fB_name\fP"
.br
.RI "Публичный геттер для имени клиента\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "int \fB_cardNumber\fP"
.br
.RI "Номер карты клиента\&. Целое число от 1 до 99999999 включительно\&. "
.ti -1c
.RI "string \fB_bankName\fP"
.br
.RI "Название обслуживающего банка\&. Строка букв русского алфавита, без пробелов и других дополнительных символов, длиной не более 20 символов, начинающаяся с заглавной буквы\&. "
.ti -1c
.RI "string \fB_name\fP"
.br
.RI "Имя клиента\&. Строка букв русского алфавита, в которой могут присутствовать разделительные символы, длиной не более 40 символов, начинающаяся с заглавной буквы\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс, описывающий клиента банковской системы\&. Обладает ключом типа int\&. 


.SH "Конструктор(ы)"
.PP 
.SS "WindowsFormsApp1\&.Client\&.Client (int cardNumber, string bankName, string name)"

.PP
Основной конструктор для создания клиента\&. 
.PP
\fBАргументы\fP
.RS 4
\fIcardNumber\fP Номер карты клиента\&. 
.br
\fIbankName\fP Название обслуживающего банка\&. 
.br
\fIname\fP Имя клиента\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "int WindowsFormsApp1\&.Client\&.Compare (\fBIElement\fP elem)"

.SS "int WindowsFormsApp1\&.Client\&.GetKey ()"

.SH "Данные класса"
.PP 
.SS "string WindowsFormsApp1\&.Client\&._bankName\fC [private]\fP"

.PP
Название обслуживающего банка\&. Строка букв русского алфавита, без пробелов и других дополнительных символов, длиной не более 20 символов, начинающаяся с заглавной буквы\&. 
.SS "int WindowsFormsApp1\&.Client\&._cardNumber\fC [private]\fP"

.PP
Номер карты клиента\&. Целое число от 1 до 99999999 включительно\&. 
.SS "string WindowsFormsApp1\&.Client\&._name\fC [private]\fP"

.PP
Имя клиента\&. Строка букв русского алфавита, в которой могут присутствовать разделительные символы, длиной не более 40 символов, начинающаяся с заглавной буквы\&. 
.SS "string WindowsFormsApp1\&.Client\&.BankName => \fB_bankName\fP"

.PP
Публичный геттер для названия обслуживающего банка\&. 
.SS "int WindowsFormsApp1\&.Client\&.CardNumber => \fB_cardNumber\fP"

.PP
Публичный геттер для номера карты\&. 
.SS "string WindowsFormsApp1\&.Client\&.Name => \fB_name\fP"

.PP
Публичный геттер для имени клиента\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
