.TH "WindowsFormsApp1.QuickStackSorter< T >" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.QuickStackSorter< T > \- Реализация сортировки для элементов типа Т\&. Использует алгоритм быстрой сортировки\&. Основан на стековой реализации алгоритма\&. Наследуется от \fBISorter\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBWindowsFormsApp1\&.ISorter< T >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBSort\fP (T[] array)"
.br
.RI "Метод, совершающий сортировку\&. "
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "int \fBPartition\fP (T[] a, int l, int r)"
.br
.RI "Функция, определяющая индекс элемента, разделяющего массив на две части\&. Меняет местами два элемента, таким образом, что они казываются в порядке возрастания\&. "
.in -1c
.SH "Подробное описание"
.PP 
Реализация сортировки для элементов типа Т\&. Использует алгоритм быстрой сортировки\&. Основан на стековой реализации алгоритма\&. Наследуется от \fBISorter\fP\&. 


.PP
\fBПараметры шаблона\fP
.RS 4
\fIT\fP Тип сортируемых данных, наследуемый от IElement\&. 
.RE
.PP

.PP
\fBСогласование типов\fP
.TP
\fIT\fP : \fIIElement\fP
.SH "Методы"
.PP 
.SS "int \fBWindowsFormsApp1\&.QuickStackSorter\fP< T >\&.Partition (T[] a, int l, int r)\fC [private]\fP"

.PP
Функция, определяющая индекс элемента, разделяющего массив на две части\&. Меняет местами два элемента, таким образом, что они казываются в порядке возрастания\&. 
.PP
\fBАргументы\fP
.RS 4
\fIa\fP Сортируемый массив\&. 
.br
\fIl\fP Левая граница разделяемой части\&. 
.br
\fIr\fP Правая граница разделяемой части\&. 
.RE
.PP
\fBВозвращает\fP
.RS 4
Индекс элемента, который делит массив на два подмассива для следующего шага сортировки\&. 
.RE
.PP

.SS "void \fBWindowsFormsApp1\&.QuickStackSorter\fP< T >\&.Sort (T[] array)"

.PP
Метод, совершающий сортировку\&. 
.PP
\fBАргументы\fP
.RS 4
\fIarray\fP Сортируемый массив\&. 
.RE
.PP

.PP
Замещает \fBWindowsFormsApp1\&.ISorter< T >\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
