.TH "WindowsFormsApp1.ShellSorter< T >" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.ShellSorter< T > \- Реализация сортировки для элементов типа Т\&. Использует алгоритм сортировки Шелла с расстоянием Шелла\&. Наследуется от \fBISorter\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBWindowsFormsApp1\&.ISorter< T >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBSort\fP (T[] array)"
.br
.RI "Метод, совершающий сортировку\&. "
.in -1c
.SH "Подробное описание"
.PP 
Реализация сортировки для элементов типа Т\&. Использует алгоритм сортировки Шелла с расстоянием Шелла\&. Наследуется от \fBISorter\fP\&. 


.PP
\fBПараметры шаблона\fP
.RS 4
\fIT\fP Тип сортируемых данных, наследуемый от IElement\&. 
.RE
.PP

.PP
\fBСогласование типов\fP
.TP
\fIT\fP : \fIIElement\fP
.SH "Методы"
.PP 
.SS "void \fBWindowsFormsApp1\&.ShellSorter\fP< T >\&.Sort (T[] array)"

.PP
Метод, совершающий сортировку\&. 
.PP
\fBАргументы\fP
.RS 4
\fIarray\fP Сортируемый массив\&. 
.RE
.PP

.PP
Замещает \fBWindowsFormsApp1\&.ISorter< T >\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
