.TH "WindowsFormsApp1.Machine" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.Machine \- Класс, описывающий банкомат\&. Обладает ключом типа int\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBWinFormsApp1\&.IKeyedElement< int >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMachine\fP (int machineNumber, string address, string bankName)"
.br
.RI "Основной конструктор для создания банкомата\&. "
.ti -1c
.RI "int \fBGetKey\fP ()"
.br
.ti -1c
.RI "int \fBCompare\fP (\fBIElement\fP elem)"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBMachineNumber\fP => \fB_machineNumber\fP"
.br
.RI "Публичный геттер для номера банкомата\&. "
.ti -1c
.RI "string \fBAddress\fP => \fB_address\fP"
.br
.RI "Публичный геттер для адреса банкомата\&. "
.ti -1c
.RI "string \fBBankName\fP => \fB_bankName\fP"
.br
.RI "Публичный геттер для названия обслуживающего банка\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "int \fB_machineNumber\fP"
.br
.RI "Номер банкомата\&. Целое число от 1 до 500 включительно\&. "
.ti -1c
.RI "string \fB_address\fP"
.br
.RI "Адрес банкомата\&. Строка букв русского алфавита без пробелов и других дополнительных символов, длиной не более 20 символов, начинающаяся с заглавной буквы (остальные строчные)\&. "
.ti -1c
.RI "string \fB_bankName\fP"
.br
.RI "Название обслуживающего банка\&. Строка букв русского алфавита, без пробелов и других дополнительных символов, длиной не более 20 символов, начинающаяся с заглавной буквы\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс, описывающий банкомат\&. Обладает ключом типа int\&. 


.SH "Конструктор(ы)"
.PP 
.SS "WindowsFormsApp1\&.Machine\&.Machine (int machineNumber, string address, string bankName)"

.PP
Основной конструктор для создания банкомата\&. 
.PP
\fBАргументы\fP
.RS 4
\fImachineNumber\fP Номер банкомата\&. 
.br
\fIaddress\fP Адрес банкомата\&. 
.br
\fIbankName\fP Название обслуживающего банка\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "int WindowsFormsApp1\&.Machine\&.Compare (\fBIElement\fP elem)"

.SS "int WindowsFormsApp1\&.Machine\&.GetKey ()"

.SH "Данные класса"
.PP 
.SS "string WindowsFormsApp1\&.Machine\&._address\fC [private]\fP"

.PP
Адрес банкомата\&. Строка букв русского алфавита без пробелов и других дополнительных символов, длиной не более 20 символов, начинающаяся с заглавной буквы (остальные строчные)\&. 
.SS "string WindowsFormsApp1\&.Machine\&._bankName\fC [private]\fP"

.PP
Название обслуживающего банка\&. Строка букв русского алфавита, без пробелов и других дополнительных символов, длиной не более 20 символов, начинающаяся с заглавной буквы\&. 
.SS "int WindowsFormsApp1\&.Machine\&._machineNumber\fC [private]\fP"

.PP
Номер банкомата\&. Целое число от 1 до 500 включительно\&. 
.SS "string WindowsFormsApp1\&.Machine\&.Address => \fB_address\fP"

.PP
Публичный геттер для адреса банкомата\&. 
.SS "string WindowsFormsApp1\&.Machine\&.BankName => \fB_bankName\fP"

.PP
Публичный геттер для названия обслуживающего банка\&. 
.SS "int WindowsFormsApp1\&.Machine\&.MachineNumber => \fB_machineNumber\fP"

.PP
Публичный геттер для номера банкомата\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
