.TH "WindowsFormsApp1.SizeContainer" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.SizeContainer \- Структура, предоставляет информацию о размере хранилища данных, для объектов, не имеющих доступа к самому хранилищу данных\&. Экранирует это данное от внешних изменений, при этом предоставляя в любой момент актуальную информацию о размере\&.  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSizeContainer\fP (int size)"
.br
.RI "Конструктор, создающий контейнер для числового данного\&. "
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "int \fBSize\fP\fC [get, set]\fP"
.br
.RI "Публичный геттер и сеттер для размера хранилища данных\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "int \fB_size\fP"
.br
.RI "Числовое представление размера хранилища данных\&. "
.in -1c
.SH "Подробное описание"
.PP 
Структура, предоставляет информацию о размере хранилища данных, для объектов, не имеющих доступа к самому хранилищу данных\&. Экранирует это данное от внешних изменений, при этом предоставляя в любой момент актуальную информацию о размере\&. 


.SH "Конструктор(ы)"
.PP 
.SS "WindowsFormsApp1\&.SizeContainer\&.SizeContainer (int size)"

.PP
Конструктор, создающий контейнер для числового данного\&. 
.PP
\fBАргументы\fP
.RS 4
\fIsize\fP Числовое представление размера\&. 
.RE
.PP

.SH "Данные класса"
.PP 
.SS "int WindowsFormsApp1\&.SizeContainer\&._size\fC [private]\fP"

.PP
Числовое представление размера хранилища данных\&. 
.SH "Полный список свойств"
.PP 
.SS "int WindowsFormsApp1\&.SizeContainer\&.Size\fC [get]\fP, \fC [set]\fP"

.PP
Публичный геттер и сеттер для размера хранилища данных\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
