.TH "WindowsFormsApp1.KeyedSearchQuery< K, V >" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.KeyedSearchQuery< K, V > \- запрос поиска для элемента, обладающего ключом\&.  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBWindowsFormsApp1\&.SearchQuery< V >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBKeyedSearchQuery\fP (V request)"
.br
.RI "Конструктор, позволяющий создать запрос с ключом\&. "
.ti -1c
.RI "K \fBSearchKey\fP ()"
.br
.RI "Возвращает ключ искомого элемента\&. "
.ti -1c
.RI "int \fBCheck\fP (T check)"
.br
.RI "Проверка элемента на соответствие искомому\&. При совпадении сохраняет проверяемое данной в качестве результирующего\&. "
.ti -1c
.RI "void \fBCount\fP ()"
.br
.RI "Позволяет увелиить значение счетчика без проведения сравнений\&. "
.ti -1c
.RI "bool \fBFound\fP ()"
.br
.RI "Сообщает найден ли элемент, соответствующий искомому\&. "
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBCounter\fP"
.br
.RI "Публичный геттер для количества проверок\&. "
.ti -1c
.RI "T \fBResult\fP"
.br
.RI "Публичный геттер для результирующего данного\&. "
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "T \fB_request\fP"
.br
.RI "Искомое данное\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "int \fB_counter\fP"
.br
.RI "Счетчик количества проверок\&. "
.ti -1c
.RI "T \fB_result\fP"
.br
.RI "Результирующее данное, соответсвующее искомому\&. "
.in -1c
.SH "Подробное описание"
.PP 
запрос поиска для элемента, обладающего ключом\&. 


.PP
\fBПараметры шаблона\fP
.RS 4
\fIK\fP Тип ключа данного\&. 
.br
\fIV\fP Тип искомого данного\&. 
.RE
.PP

.PP
\fBСогласование типов\fP
.TP
\fIV\fP : \fIIKeyedElement<K>\fP
.SH "Конструктор(ы)"
.PP 
.SS "\fBWindowsFormsApp1\&.KeyedSearchQuery\fP< K, V >\&.\fBKeyedSearchQuery\fP (V request)"

.PP
Конструктор, позволяющий создать запрос с ключом\&. 
.PP
\fBАргументы\fP
.RS 4
\fIrequest\fP Искомый элемент\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "int \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&.Check (T check)\fC [inherited]\fP"

.PP
Проверка элемента на соответствие искомому\&. При совпадении сохраняет проверяемое данной в качестве результирующего\&. 
.PP
\fBАргументы\fP
.RS 4
\fIcheck\fP Проверяемое данное\&. 
.RE
.PP
\fBВозвращает\fP
.RS 4
Отрицательное число, если этот элемент меньше, чем поступающий на вход\&. Ноль, если элементы равны\&. Положительное число, если этот элемент больше, чем поступающий на вход\&. 
.RE
.PP

.SS "void \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&.Count\fC [inherited]\fP"

.PP
Позволяет увелиить значение счетчика без проведения сравнений\&. 
.SS "bool \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&.Found\fC [inherited]\fP"

.PP
Сообщает найден ли элемент, соответствующий искомому\&. 
.PP
\fBВозвращает\fP
.RS 4
True, если элемент найден, false в ином случае\&. 
.RE
.PP

.SS "K \fBWindowsFormsApp1\&.KeyedSearchQuery\fP< K, V >\&.SearchKey ()"

.PP
Возвращает ключ искомого элемента\&. 
.PP
\fBВозвращает\fP
.RS 4
Ключ искомого элемента\&. 
.RE
.PP

.SH "Данные класса"
.PP 
.SS "int \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&._counter\fC [private]\fP, \fC [inherited]\fP"

.PP
Счетчик количества проверок\&. 
.SS "T \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&._request\fC [protected]\fP, \fC [inherited]\fP"

.PP
Искомое данное\&. 
.SS "T \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&._result\fC [private]\fP, \fC [inherited]\fP"

.PP
Результирующее данное, соответсвующее искомому\&. 
.SS "int \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&.Counter\fC [inherited]\fP"

.PP
Публичный геттер для количества проверок\&. 
.SS "T \fBWindowsFormsApp1\&.SearchQuery\fP< T >\&.Result\fC [inherited]\fP"

.PP
Публичный геттер для результирующего данного\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
