.TH "WindowsFormsApp1" 3 "Сб 27 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBBubbleSorter\fP"
.br
.RI "Реализация сортировки для элементов типа Т\&. Использует алгоритм сортировки пузырьком\&. Наследуется от \fBISorter\fP\&. "
.ti -1c
.RI "class \fBChecks\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.RI "Класс, описывающий клиента банковской системы\&. Обладает ключом типа int\&. "
.ti -1c
.RI "class \fBClientFound\fP"
.br
.ti -1c
.RI "class \fBDatabase\fP"
.br
.RI "Класс-оболочка базы данных, предоставляющий доступ ко всем методам, необходимым для работы со структурами данных\&. Реализует шаблон проектирования Singleton\&. Предоставляет возможности для сохранения и загрузки базы данных на жесткий диск, при помощи сериализации\&. "
.ti -1c
.RI "class \fBErrorForm\fP"
.br
.ti -1c
.RI "class \fBGUI\fP"
.br
.ti -1c
.RI "class \fBHashMap1Dialog\fP"
.br
.ti -1c
.RI "class \fBHashMap2Dialog\fP"
.br
.ti -1c
.RI "interface \fBISorter\fP"
.br
.RI "Интерфейс, описывающий сортировщик элементов типа Т\&. "
.ti -1c
.RI "class \fBKeyedSearchQuery\fP"
.br
.RI "запрос поиска для элемента, обладающего ключом\&. "
.ti -1c
.RI "class \fBMachine\fP"
.br
.RI "Класс, описывающий банкомат\&. Обладает ключом типа int\&. "
.ti -1c
.RI "class \fBMachineFound\fP"
.br
.ti -1c
.RI "class \fBModFunction\fP"
.br
.RI "Функция, определяющая хэш делением\&. "
.ti -1c
.RI "class \fBOddFunction\fP"
.br
.RI "Функция, генерируяшая нечетные хэши, в пределах размера хранилища\&. "
.ti -1c
.RI "class \fBOperation\fP"
.br
.RI "Класс, описывающий банковскую операцию\&. "
.ti -1c
.RI "class \fBoperationFound\fP"
.br
.ti -1c
.RI "class \fBOperationsOfClient\fP"
.br
.ti -1c
.RI "class \fBOperationsOfMachine\fP"
.br
.ti -1c
.RI "class \fBPercent\fP"
.br
.RI "Класс, описывающий процент по операции\&. "
.ti -1c
.RI "class \fBpercentFound\fP"
.br
.ti -1c
.RI "class \fBPercentsOfMachine\fP"
.br
.ti -1c
.RI "class \fBPercentsOfOperation\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBQuickLastSorter\fP"
.br
.RI "Реализация сортировки для элементов типа Т\&. Использует алгоритм сортировки пузырьком\&. Наследуется от \fBISorter\fP\&. "
.ti -1c
.RI "class \fBQuickStackSorter\fP"
.br
.RI "Реализация сортировки для элементов типа Т\&. Использует алгоритм быстрой сортировки\&. Основан на стековой реализации алгоритма\&. Наследуется от \fBISorter\fP\&. "
.ti -1c
.RI "class \fBRB\fP"
.br
.ti -1c
.RI "class \fBReport\fP"
.br
.RI "Отчет о данных, соответствующих запросу\&. Ищет все данные, соответсвующие запросу и сортирует их используя \fBISorter\fP\&. "
.ti -1c
.RI "class \fBResult\fP"
.br
.RI "Позволяет возвращать результат выполнения действия, содержащий информацию об успешности и описание события\&. "
.ti -1c
.RI "class \fBSearchQuery\fP"
.br
.RI "Поисковый запрос, предостаавляющий возможности сравнения проверяемого элемента с искомым, который считает количество проверок\&. "
.ti -1c
.RI "class \fBShellSorter\fP"
.br
.RI "Реализация сортировки для элементов типа Т\&. Использует алгоритм сортировки Шелла с расстоянием Шелла\&. Наследуется от \fBISorter\fP\&. "
.ti -1c
.RI "class \fBSizeContainer\fP"
.br
.RI "Структура, предоставляет информацию о размере хранилища данных, для объектов, не имеющих доступа к самому хранилищу данных\&. Экранирует это данное от внешних изменений, при этом предоставляя в любой момент актуальную информацию о размере\&. "
.ti -1c
.RI "class \fBSplash\fP"
.br
.ti -1c
.RI "class \fBTree1Dialog\fP"
.br
.ti -1c
.RI "class \fBTree2Dialog\fP"
.br
.ti -1c
.RI "class \fBWaterMarkTextBox\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
