.TH "WindowsFormsApp1.RB< T >.Node< T >" 3 "Вс 28 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApp1.RB< T >.Node< T > \- Object of type \fBNode\fP contains 4 properties Colour Left Right Parent Data  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBNode\fP (T \fBdata\fP)"
.br
.ti -1c
.RI "\fBNode\fP (\fBColor\fP \fBcolour\fP)"
.br
.ti -1c
.RI "\fBNode\fP (T \fBdata\fP, \fBColor\fP \fBcolour\fP)"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBColor\fP \fBcolour\fP"
.br
.ti -1c
.RI "\fBNode\fP< T > \fBleft\fP"
.br
.ti -1c
.RI "\fBNode\fP< T > \fBright\fP"
.br
.ti -1c
.RI "\fBNode\fP< T > \fBparent\fP"
.br
.ti -1c
.RI "T \fBdata\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Object of type \fBNode\fP contains 4 properties Colour Left Right Parent Data 


.SH "Конструктор(ы)"
.PP 
.SS "\fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.\fBNode\fP (T data)"

.SS "\fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.\fBNode\fP (\fBColor\fP colour)"

.SS "\fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.\fBNode\fP (T data, \fBColor\fP colour)"

.SH "Данные класса"
.PP 
.SS "\fBColor\fP \fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.colour"

.SS "T \fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.data"

.SS "\fBNode\fP<T> \fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.left"

.SS "\fBNode\fP<T> \fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.parent"

.SS "\fBNode\fP<T> \fBWindowsFormsApp1\&.RB\fP< T >\&.\fBNode\fP< T >\&.right"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
