.TH "WinFormsApp1.DoubleHashStorage< K, V >" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WinFormsApp1.DoubleHashStorage< K, V >
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBWinFormsApp1\&.Storage< K, V >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBDoubleHashStorage\fP (\fBHashFunction\fP< K > mainFunction, \fBHashFunction\fP< K > outsideFunction)"
.br
.RI "Конструктор, получающий на вход хуш-функции, предоставляющий им информацию о размере, а также заполняет массив _deleted\&. "
.ti -1c
.RI "override int \fBGetSize\fP ()"
.br
.RI "Геттер, возвращающий размер хранилища в числовом представлении\&. "
.ti -1c
.RI "override void \fBAdd\fP (int index, V element)"
.br
.RI "Добавляет элемент в хранилище\&. "
.ti -1c
.RI "override bool \fBRemove\fP (int index, V element)"
.br
.RI "Удаляет элемент из хранилища\&. "
.ti -1c
.RI "override V[] \fBToArray\fP ()"
.br
.RI "Возвращает элементы хранилища в виде массива\&. "
.ti -1c
.RI "override void \fBFind\fP (int index, \fBKeyedSearchQuery\fP< K, V > keyedQuery)"
.br
.RI "Поиск указанного в запросе элемента, по указанному индексу хранилища, учитывая стратегии разрешения коллизий\&. "
.ti -1c
.RI "\fBSizeContainer\fP \fBSizeContainer\fP ()"
.br
.RI "Публичный геттер для контейнера, содержащего размер хранилища\&. "
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBInflate\fP ()"
.br
.RI "Функция, позволяющая увеличить размер хранилища в два раза\&. Также обновляет положение всех элементов, в соответствии с новыми значениями хэш-функций\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fBHashFunction\fP< K > \fB_mainFunction\fP"
.br
.RI "Основная хэш-функция данного хранилища\&. "
.ti -1c
.RI "\fBHashFunction\fP< K > \fB_outsideFunction\fP"
.br
.RI "Внешняя функция, предоставленная хэш-таблицей\&. "
.ti -1c
.RI "V[] \fB_array\fP = new V[16]"
.br
.RI "Массив элементов, содержащихся в этом хранилище\&. "
.ti -1c
.RI "bool[] \fB_deleted\fP = new bool[16]"
.br
.RI "Массив указателей на то, был ли удален элемент из данной ячейки\&. "
.ti -1c
.RI "int \fB_size\fP = 0"
.br
.RI "Количество элементов, содержащихся в хранилище\&. "
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "\fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.\fBDoubleHashStorage\fP (\fBHashFunction\fP< K > mainFunction, \fBHashFunction\fP< K > outsideFunction)"

.PP
Конструктор, получающий на вход хуш-функции, предоставляющий им информацию о размере, а также заполняет массив _deleted\&. 
.PP
\fBАргументы\fP
.RS 4
\fImainFunction\fP Основная хэш-функция\&. 
.br
\fIoutsideFunction\fP Внешняя функция, предоставленная хэш-таблицей\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "override void \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.Add (int index, V element)\fC [virtual]\fP"

.PP
Добавляет элемент в хранилище\&. 
.PP
\fBАргументы\fP
.RS 4
\fIindex\fP Индекс в хранилище, опеделенный хэш функцией таблицы\&. 
.br
\fIelement\fP Добавляемый элемент\&. 
.RE
.PP

.PP
Замещает \fBWinFormsApp1\&.Storage< K, V >\fP\&.
.SS "override void \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.Find (int index, \fBKeyedSearchQuery\fP< K, V > keyedQuery)\fC [virtual]\fP"

.PP
Поиск указанного в запросе элемента, по указанному индексу хранилища, учитывая стратегии разрешения коллизий\&. 
.PP
\fBАргументы\fP
.RS 4
\fIindex\fP Индекс, по которому в хранилище должен располагаться данный объект, если он в нем присутствует\&. Определяется хэш-функцией\&. 
.br
\fIkeyedQuery\fP Поисковый запрос, содержащий искомый объект\&. 
.RE
.PP

.PP
Замещает \fBWinFormsApp1\&.Storage< K, V >\fP\&.
.SS "override int \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.GetSize ()\fC [virtual]\fP"

.PP
Геттер, возвращающий размер хранилища в числовом представлении\&. 
.PP
\fBВозвращает\fP
.RS 4
Числовое представление размера хранилища\&. 
.RE
.PP

.PP
Замещает \fBWinFormsApp1\&.Storage< K, V >\fP\&.
.SS "void \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.Inflate ()\fC [private]\fP"

.PP
Функция, позволяющая увеличить размер хранилища в два раза\&. Также обновляет положение всех элементов, в соответствии с новыми значениями хэш-функций\&. 
.SS "override bool \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.Remove (int index, V element)\fC [virtual]\fP"

.PP
Удаляет элемент из хранилища\&. 
.PP
\fBАргументы\fP
.RS 4
\fIindex\fP Индекс в хранилище, опеделенный хэш функцией таблицы\&. 
.br
\fIelement\fP Удаляемый элемент\&. 
.RE
.PP
\fBВозвращает\fP
.RS 4
Возвращает true если элемент успешно удален и false в остальных случаях\&. 
.RE
.PP

.PP
Замещает \fBWinFormsApp1\&.Storage< K, V >\fP\&.
.SS "\fBSizeContainer\fP \fBWinFormsApp1\&.Storage\fP< K, V >\&.\fBSizeContainer\fP ()\fC [inherited]\fP"

.PP
Публичный геттер для контейнера, содержащего размер хранилища\&. 
.PP
\fBВозвращает\fP
.RS 4

.RE
.PP

.SS "override V [] \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&.ToArray ()\fC [virtual]\fP"

.PP
Возвращает элементы хранилища в виде массива\&. 
.PP
\fBВозвращает\fP
.RS 4
Массив, состоящий из элементов хранилища\&. 
.RE
.PP

.PP
Замещает \fBWinFormsApp1\&.Storage< K, V >\fP\&.
.SH "Данные класса"
.PP 
.SS "V [] \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&._array = new V[16]\fC [private]\fP"

.PP
Массив элементов, содержащихся в этом хранилище\&. 
.SS "bool [] \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&._deleted = new bool[16]\fC [private]\fP"

.PP
Массив указателей на то, был ли удален элемент из данной ячейки\&. 
.SS "\fBHashFunction\fP<K> \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&._mainFunction\fC [private]\fP"

.PP
Основная хэш-функция данного хранилища\&. 
.SS "\fBHashFunction\fP<K> \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&._outsideFunction\fC [private]\fP"

.PP
Внешняя функция, предоставленная хэш-таблицей\&. 
.SS "int \fBWinFormsApp1\&.DoubleHashStorage\fP< K, V >\&._size = 0\fC [private]\fP"

.PP
Количество элементов, содержащихся в хранилище\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
