.TH "WinFormsApp1.Tree< T >.Position< T >" 3 "Вс 7 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WinFormsApp1.Tree< T >.Position< T > \- Вершина дерева, реализующий методы работы с поддервом\&.  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBPosition\fP (T element)"
.br
.RI "Конструктор, создающий вершину дерева\&. "
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "T \fBElement\fP\fC [get, set]\fP"
.br
.RI "Публичный геттер и сеттер для элемента, хранимого в вершине\&. "
.ti -1c
.RI "\fBPosition\fP< T > \fBLeftChild\fP\fC [get, set]\fP"
.br
.RI "Публичный геттер и сеттер для левой ветви поддерева\&. "
.ti -1c
.RI "\fBPosition\fP< T > \fBRightChild\fP\fC [get, set]\fP"
.br
.RI "Публичный геттер и сеттер для правой ветви поддерева\&. "
.ti -1c
.RI "\fBPosition\fP< T > \fBCenterChild\fP\fC [get, set]\fP"
.br
.RI "Публичный геттер и сеттер для центральной ветви поддерева\&. "
.ti -1c
.RI "\fBPosition\fP< T > \fBParent\fP\fC [get, set]\fP"
.br
.RI "Публичный геттер и сеттер для родителя этой вершины\&. "
.in -1c
.SH "Подробное описание"
.PP 
Вершина дерева, реализующий методы работы с поддервом\&. 


.PP
\fBПараметры шаблона\fP
.RS 4
\fIT\fP Тип данных, хранимых в дереве\&. 
.RE
.PP

.PP
\fBСогласование типов\fP
.TP
\fIT\fP : \fI\fBIElement\fP\fP
.SH "Конструктор(ы)"
.PP 
.SS "\fBWinFormsApp1\&.Tree\fP< T >\&.\fBPosition\fP< T >\&.\fBPosition\fP (T element)"

.PP
Конструктор, создающий вершину дерева\&. 
.PP
\fBАргументы\fP
.RS 4
\fIelement\fP Элемент, хранимый в вершине дерева\&. 
.RE
.PP

.SH "Полный список свойств"
.PP 
.SS "\fBPosition\fP<T> \fBWinFormsApp1\&.Tree\fP< T >\&.\fBPosition\fP< T >\&.CenterChild\fC [get]\fP, \fC [set]\fP"

.PP
Публичный геттер и сеттер для центральной ветви поддерева\&. 
.SS "T \fBWinFormsApp1\&.Tree\fP< T >\&.\fBPosition\fP< T >\&.Element\fC [get]\fP, \fC [set]\fP"

.PP
Публичный геттер и сеттер для элемента, хранимого в вершине\&. 
.SS "\fBPosition\fP<T> \fBWinFormsApp1\&.Tree\fP< T >\&.\fBPosition\fP< T >\&.LeftChild\fC [get]\fP, \fC [set]\fP"

.PP
Публичный геттер и сеттер для левой ветви поддерева\&. 
.SS "\fBPosition\fP<T> \fBWinFormsApp1\&.Tree\fP< T >\&.\fBPosition\fP< T >\&.Parent\fC [get]\fP, \fC [set]\fP"

.PP
Публичный геттер и сеттер для родителя этой вершины\&. 
.SS "\fBPosition\fP<T> \fBWinFormsApp1\&.Tree\fP< T >\&.\fBPosition\fP< T >\&.RightChild\fC [get]\fP, \fC [set]\fP"

.PP
Публичный геттер и сеттер для правой ветви поддерева\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
