.TH "WinFormsApp1" 3 "Вс 28 Июн 2020" "Inkostilation Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WinFormsApp1
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBDoubleHashStorage\fP"
.br
.ti -1c
.RI "class \fBHashFunction\fP"
.br
.RI "Хэш-функция, предоставляющая индекс, соответствующий поступившему на вход данному\&. "
.ti -1c
.RI "class \fBHashMap\fP"
.br
.ti -1c
.RI "interface \fBICollection\fP"
.br
.RI "Интерфейс, описывающий методы коллекции данных\&. "
.ti -1c
.RI "interface \fBIElement\fP"
.br
.RI "Интерфейс, описывающий данное, хранящееся в базе\&. "
.ti -1c
.RI "interface \fBIKeyedElement\fP"
.br
.RI "Интерфейс, описывающий элемент, обладающий ключом, используемым для генерации хэш-функции\&. "
.ti -1c
.RI "class \fBListStorage\fP"
.br
.ti -1c
.RI "class \fBStorage\fP"
.br
.RI "Внутренняя структура хэш-таблицы\&. хранящая все данные и реализующая стратегии разрешения коллизий\&. "
.ti -1c
.RI "class \fBTree\fP"
.br
.RI "Коллекция вида бинарное дерево\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Inkostilation Project из исходного текста\&.
