WinFormsApp1::HashFunction
SizeContainer WinFormsApp1.HashFunction< T >._size
Структура для хранения количества элементов внутреннего хранилища и динамического обращения к нему объектов, не имеющих доступ к самому хранилищу.
Referenced by WinFormsApp1.HashFunction< K >::SetSize.
void WinFormsApp1.HashFunction< T >.SetSize(SizeContainer size)
Публичный сеттер, позволяющий заменить размер хранилища на новый.
size Новый контейнер, содержащий размер.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.DoubleHashStorage, WinFormsApp1.HashMap< int, WindowsFormsApp1.Client >::HashMap.
abstract int WinFormsApp1.HashFunction< T >.Hash(T key)
Преобразует хэшируемое данное в индекс.
key Данное для хэширования. Индекс, полученные хэшированием данных.
Referenced by WinFormsApp1.HashMap< int, WindowsFormsApp1.Client >::Add, WinFormsApp1.DoubleHashStorage< K, V >.Add, WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button3_Click, WinFormsApp1.HashMap< int, WindowsFormsApp1.Client >::Find, WinFormsApp1.DoubleHashStorage< K, V >.Find, WinFormsApp1.DoubleHashStorage< K, V >.Inflate, WinFormsApp1.HashMap< int, WindowsFormsApp1.Client >::Remove, WinFormsApp1.DoubleHashStorage< K, V >.Remove, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click.
int WinFormsApp1.HashFunction< T >.GetStorageSize()
Возвразает числовое представление размера.
Числовое представление размера.