WindowsFormsApp1::Tree1Dialog
System.ComponentModel.IContainer WindowsFormsApp1.Tree1Dialog.components
Required designer variable.
Referenced by WindowsFormsApp1.Tree1Dialog.Dispose.
System.Windows.Forms.Label WindowsFormsApp1.Tree1Dialog.label4
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.Tree1Dialog.button1
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.Tree1Dialog.label3
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.Tree1Dialog.label2
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.Tree1Dialog.label1
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.Tree1Dialog.label5
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.Tree1Dialog.button2
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
WaterMarkTextBox WindowsFormsApp1.Tree1Dialog.waterMarkTextBox1
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.Tree1Dialog.button1_Click, WindowsFormsApp1.Tree1Dialog.InitializeComponent.
WaterMarkTextBox WindowsFormsApp1.Tree1Dialog.waterMarkTextBox2
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.Tree1Dialog.button1_Click, WindowsFormsApp1.Tree1Dialog.InitializeComponent.
WaterMarkTextBox WindowsFormsApp1.Tree1Dialog.waterMarkTextBox3
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.Tree1Dialog.button1_Click, WindowsFormsApp1.Tree1Dialog.InitializeComponent.
WaterMarkTextBox WindowsFormsApp1.Tree1Dialog.waterMarkTextBox4
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.Tree1Dialog.button1_Click, WindowsFormsApp1.Tree1Dialog.InitializeComponent.
WindowsFormsApp1.Tree1Dialog.Tree1Dialog()
References WindowsFormsApp1.Tree1Dialog.InitializeComponent.
void WindowsFormsApp1.Tree1Dialog.button1_Click(object sender, EventArgs e)
References WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox1, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox2, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox3, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox4.
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
void WindowsFormsApp1.Tree1Dialog.button2_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.stopflag.
Referenced by WindowsFormsApp1.Tree1Dialog.InitializeComponent.
void WindowsFormsApp1.Tree1Dialog.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References WindowsFormsApp1.Tree1Dialog.button1, WindowsFormsApp1.Tree1Dialog.button1_Click, WindowsFormsApp1.Tree1Dialog.button2, WindowsFormsApp1.Tree1Dialog.button2_Click, WindowsFormsApp1.Tree1Dialog.label1, WindowsFormsApp1.Tree1Dialog.label2, WindowsFormsApp1.Tree1Dialog.label3, WindowsFormsApp1.Tree1Dialog.label4, WindowsFormsApp1.Tree1Dialog.label5, WindowsFormsApp1.WaterMarkTextBox.WaterMarkColor, WindowsFormsApp1.WaterMarkTextBox.WaterMarkText, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox1, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox2, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox3, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox4.
Referenced by WindowsFormsApp1.Tree1Dialog.Tree1Dialog.
override void WindowsFormsApp1.Tree1Dialog.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References WindowsFormsApp1.Tree1Dialog.components.