WindowsFormsApp1::Report
K WindowsFormsApp1.Report< K, V >._key
Данное, предоставленное в качестве запроса.
Referenced by WindowsFormsApp1.Report< K, V >.Report.
Container<V> WindowsFormsApp1.Report< K, V >._root
Первый элемент списка результирующих данных.
Referenced by WindowsFormsApp1.Report< K, V >.Add, WindowsFormsApp1.Report< K, V >.Data, WindowsFormsApp1.Report< K, V >.DataSize.
ISorter<V> WindowsFormsApp1.Report< K, V >._sorter
Объект-сортировщик, применяемый над данными.
Referenced by WindowsFormsApp1.Report< K, V >.Report, WindowsFormsApp1.Report< K, V >.Data.
K WindowsFormsApp1.Report< K, V >.Key
Публичный геттер для предоставленного в запросе данного.
WindowsFormsApp1.Report< K, V >.Report(K key, ISorter< V > sorter)
Конструктор, позволяющий инициализировать запрос на создание отчета.
key Данное-запрос, в соответствии с которым создается отчет. sorter Сортировщик результирующих данных.
References WindowsFormsApp1.Report< K, V >._key, WindowsFormsApp1.Report< K, V >._sorter.
void WindowsFormsApp1.Report< K, V >.Add(V element)
Добавляет элемент в отчет.
element Добавляемый элемент.
References WindowsFormsApp1.Report< K, V >._root, WindowsFormsApp1.Report< K, V >.Container< T >.Add.
Referenced by WindowsFormsApp1.Database.ClientOperationReport, WindowsFormsApp1.Database.MachineOperationReport, WindowsFormsApp1.Database.MachinePercentReport, WindowsFormsApp1.Database.OperationPercentReport.
V [] WindowsFormsApp1.Report< K, V >.Data()
Предоставляет данные, хранящиеся в отчете в виде массива.
Массив данных, хранящихся в отчете.
References WindowsFormsApp1.Report< K, V >._root, WindowsFormsApp1.Report< K, V >._sorter, WindowsFormsApp1.Report< K, V >.Container< T >.Fill, WindowsFormsApp1.Report< K, V >.Container< T >.Size, WindowsFormsApp1.ISorter< T >.Sort.
Referenced by WindowsFormsApp1.OperationsOfClient.ClientsKey_CellClick, WindowsFormsApp1.OperationsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfOperation.OperationsKey_CellClick, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click.
int WindowsFormsApp1.Report< K, V >.DataSize()
Возвращает количество элементов в отчете.
Количество элементов в отчете.
References WindowsFormsApp1.Report< K, V >._root, WindowsFormsApp1.Report< K, V >.Container< T >.Size.
Referenced by WindowsFormsApp1.OperationsOfClient.ClientsKey_CellClick, WindowsFormsApp1.OperationsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfOperation.OperationsKey_CellClick, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click.