WindowsFormsApp1::Checks
static Result WindowsFormsApp1.Checks.CheckMachine(string number, string address, string bankName)
Проверка входных данных на соответствие условиям банкомата.
number Номер банкомата. address Адрес банкомата. bankName Название банка. Результат о соответствии данных условиям для банкомата.
References WindowsFormsApp1.Result.AddMessage, WindowsFormsApp1.Result.Message, WindowsFormsApp1.Result.Success.
Referenced by WindowsFormsApp1.Database.LoadInstance.
static Result WindowsFormsApp1.Checks.CheckClient(string cardNumber, string bankName, string clientName)
Проверка входных данных на соответствие условиям клиента.
cardNumber Номер карты клиента. bankName Имя банка, обслуживающего клиента. clientName ФИО клиента. Результат о соответствии данных условиям для клиента.
References WindowsFormsApp1.Result.AddMessage, WindowsFormsApp1.Result.Message, WindowsFormsApp1.Result.Success.
Referenced by WindowsFormsApp1.Database.LoadInstance.
static Result WindowsFormsApp1.Checks.CheckPercent(string operationName, string sender, string receiver, string percent)
Проверка входных данных на соответствие условиям процента операции.
operationName Название операции. sender Банк отправитель. receiver Банк получатель. percent Процент операции. Результат о соответствии данных условиям для процента операции.
References WindowsFormsApp1.Result.AddMessage, WindowsFormsApp1.Result.Message, WindowsFormsApp1.Result.Success.
Referenced by WindowsFormsApp1.Database.LoadInstance.
static Result WindowsFormsApp1.Checks.CheckOperation(string name, string cardNumber, string machineNumber, string sum)
Проверка входных данных на соответствие условиям операции.
name Название операции. cardNumber Номер карты. machineNumber Номер банкомата. sum Сумма операции. Результат о соответствии данных условиям для операции.
References WindowsFormsApp1.Result.AddMessage, WindowsFormsApp1.Result.Message, WindowsFormsApp1.Result.Success.
Referenced by WindowsFormsApp1.Database.LoadInstance.