WinFormsApp1::ListStorage
Position<V> [] WinFormsApp1.ListStorage< K, V >.array
Массив списков, представляющий структуру хранения данных.
Referenced by WinFormsApp1.ListStorage< K, V >.ListStorage, WinFormsApp1.ListStorage< K, V >.GetSize, WinFormsApp1.ListStorage< K, V >.Add, WinFormsApp1.ListStorage< K, V >.Remove, WinFormsApp1.ListStorage< K, V >.ToArray, WinFormsApp1.ListStorage< K, V >.Find, WinFormsApp1.ListStorage< K, V >.Position< V >::FillArray.
SizeContainer WinFormsApp1.Storage< K, V >._size
Структура для хранения количества элементов внутреннего хранилища и динамического обращения к нему объектов, не имеющих доступ к самому хранилищу.
Referenced by WinFormsApp1.Storage< K, V >.Storage, WinFormsApp1.Storage< K, V >.SizeContainer.
WinFormsApp1.ListStorage< K, V >.ListStorage()
Инициализирует массив объектов Position размером в 10 элементов. Также вызывает конструктор базового класса Storage с тем же размером.
References WinFormsApp1.ListStorage< K, V >.array.
override int WinFormsApp1.ListStorage< K, V >.GetSize()
Геттер, возвращающий размер хранилища в числовом представлении.
Числовое представление размера хранилища.
References WinFormsApp1.ListStorage< K, V >.array.
Referenced by WinFormsApp1.ListStorage< K, V >.ToArray.
override void WinFormsApp1.ListStorage< K, V >.Add(int index, V element)
Добавляет элемент в хранилище.
index Индекс в хранилище, опеделенный хэш функцией таблицы. element Добавляемый элемент.
References WinFormsApp1.ListStorage< K, V >.Position< T >.Add, WinFormsApp1.ListStorage< K, V >.array.
override bool WinFormsApp1.ListStorage< K, V >.Remove(int index, V element)
Удаляет элемент из хранилища.
index Индекс в хранилище, опеделенный хэш функцией таблицы. element Удаляемый элемент. Возвращает true если элемент успешно удален и false в остальных случаях.
References WinFormsApp1.ListStorage< K, V >.array, WinFormsApp1.ListStorage< K, V >.Position< T >.Remove.
override V [] WinFormsApp1.ListStorage< K, V >.ToArray()
Возвращает элементы хранилища в виде массива.
Массив, состоящий из элементов хранилища.
References WinFormsApp1.ListStorage< K, V >.array, WinFormsApp1.ListStorage< K, V >.GetSize.
override void WinFormsApp1.ListStorage< K, V >.Find(int index, KeyedSearchQuery< K, V > keyedQuery)
Поиск указанного в запросе элемента, по указанному индексу хранилища, учитывая стратегии разрешения коллизий.
index Индекс, по которому в хранилище должен располагаться данный объект, если он в нем присутствует. Определяется хэш-функцией. keyedQuery Поисковый запрос, содержащий искомый объект.
References WinFormsApp1.ListStorage< K, V >.array.
Referenced by WinFormsApp1.ListStorage< K, V >.Find.
SizeContainer WinFormsApp1.Storage< K, V >.SizeContainer()
Публичный геттер для контейнера, содержащего размер хранилища.
References WinFormsApp1.Storage< K, V >._size.
Referenced by WinFormsApp1.HashMap< int, WindowsFormsApp1.Client >::HashMap, WinFormsApp1.Storage< K, V >.Storage.
void WinFormsApp1.ListStorage< K, V >.Find(Position< V > position, KeyedSearchQuery< K, V > keyedQuery)
Внутренний рекурсивный метод поиска. Проходит по списку Position, находящихся после этой. Останавливается при обнаружении нужного элемента или по окончании списка.
position Позиция, в которой ведется поиск. keyedQuery Поисковый запрос, содержащий искомый объект.
References WindowsFormsApp1.SearchQuery< V >::Check, WindowsFormsApp1.SearchQuery< V >::Count, WinFormsApp1.ListStorage< K, V >.Position< T >.Element, WinFormsApp1.ListStorage< K, V >.Find, WinFormsApp1.ListStorage< K, V >.Position< T >.Next.