WinFormsApp1::DoubleHashStorage
HashFunction<K> WinFormsApp1.DoubleHashStorage< K, V >._mainFunction
Основная хэш-функция данного хранилища.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.DoubleHashStorage, WinFormsApp1.DoubleHashStorage< K, V >.Add, WinFormsApp1.DoubleHashStorage< K, V >.Remove, WinFormsApp1.DoubleHashStorage< K, V >.Find.
HashFunction<K> WinFormsApp1.DoubleHashStorage< K, V >._outsideFunction
Внешняя функция, предоставленная хэш-таблицей.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.DoubleHashStorage, WinFormsApp1.DoubleHashStorage< K, V >.Inflate.
V [] WinFormsApp1.DoubleHashStorage< K, V >._array
Массив элементов, содержащихся в этом хранилище.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.Add, WinFormsApp1.DoubleHashStorage< K, V >.Inflate, WinFormsApp1.DoubleHashStorage< K, V >.Remove, WinFormsApp1.DoubleHashStorage< K, V >.ToArray, WinFormsApp1.DoubleHashStorage< K, V >.Find.
bool [] WinFormsApp1.DoubleHashStorage< K, V >._deleted
Массив указателей на то, был ли удален элемент из данной ячейки.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.DoubleHashStorage, WinFormsApp1.DoubleHashStorage< K, V >.Add, WinFormsApp1.DoubleHashStorage< K, V >.Inflate, WinFormsApp1.DoubleHashStorage< K, V >.Remove, WinFormsApp1.DoubleHashStorage< K, V >.ToArray, WinFormsApp1.DoubleHashStorage< K, V >.Find.
int WinFormsApp1.DoubleHashStorage< K, V >._size
Количество элементов, содержащихся в хранилище.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.GetSize, WinFormsApp1.DoubleHashStorage< K, V >.Add, WinFormsApp1.DoubleHashStorage< K, V >.Inflate, WinFormsApp1.DoubleHashStorage< K, V >.Remove.
WinFormsApp1.DoubleHashStorage< K, V >.DoubleHashStorage(HashFunction< K > mainFunction, HashFunction< K > outsideFunction)
Конструктор, получающий на вход хуш-функции, предоставляющий им информацию о размере, а также заполняет массив _deleted.
mainFunction Основная хэш-функция. outsideFunction Внешняя функция, предоставленная хэш-таблицей.
References WinFormsApp1.DoubleHashStorage< K, V >._deleted, WinFormsApp1.DoubleHashStorage< K, V >._mainFunction, WinFormsApp1.DoubleHashStorage< K, V >._outsideFunction, WinFormsApp1.HashFunction< T >.SetSize.
override int WinFormsApp1.DoubleHashStorage< K, V >.GetSize()
Геттер, возвращающий размер хранилища в числовом представлении.
Числовое представление размера хранилища.
References WinFormsApp1.DoubleHashStorage< K, V >._size.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.ToArray.
override void WinFormsApp1.DoubleHashStorage< K, V >.Add(int index, V element)
Добавляет элемент в хранилище.
index Индекс в хранилище, опеделенный хэш функцией таблицы. element Добавляемый элемент.
References WinFormsApp1.DoubleHashStorage< K, V >._array, WinFormsApp1.DoubleHashStorage< K, V >._deleted, WinFormsApp1.DoubleHashStorage< K, V >._mainFunction, WinFormsApp1.DoubleHashStorage< K, V >._size, WinFormsApp1.HashFunction< T >.Hash, WinFormsApp1.DoubleHashStorage< K, V >.Inflate.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.Inflate.
override bool WinFormsApp1.DoubleHashStorage< K, V >.Remove(int index, V element)
Удаляет элемент из хранилища.
index Индекс в хранилище, опеделенный хэш функцией таблицы. element Удаляемый элемент. Возвращает true если элемент успешно удален и false в остальных случаях.
References WinFormsApp1.DoubleHashStorage< K, V >._array, WinFormsApp1.DoubleHashStorage< K, V >._deleted, WinFormsApp1.DoubleHashStorage< K, V >._mainFunction, WinFormsApp1.DoubleHashStorage< K, V >._size, WinFormsApp1.HashFunction< T >.Hash.
override V [] WinFormsApp1.DoubleHashStorage< K, V >.ToArray()
Возвращает элементы хранилища в виде массива.
Массив, состоящий из элементов хранилища.
References WinFormsApp1.DoubleHashStorage< K, V >._array, WinFormsApp1.DoubleHashStorage< K, V >._deleted, WinFormsApp1.DoubleHashStorage< K, V >.GetSize.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.Inflate.
override void WinFormsApp1.DoubleHashStorage< K, V >.Find(int index, KeyedSearchQuery< K, V > keyedQuery)
Поиск указанного в запросе элемента, по указанному индексу хранилища, учитывая стратегии разрешения коллизий.
index Индекс, по которому в хранилище должен располагаться данный объект, если он в нем присутствует. Определяется хэш-функцией. keyedQuery Поисковый запрос, содержащий искомый объект.
References WinFormsApp1.DoubleHashStorage< K, V >._array, WinFormsApp1.DoubleHashStorage< K, V >._deleted, WinFormsApp1.DoubleHashStorage< K, V >._mainFunction, WindowsFormsApp1.SearchQuery< V >::Check, WindowsFormsApp1.SearchQuery< V >::Count, WinFormsApp1.HashFunction< T >.Hash, WindowsFormsApp1.KeyedSearchQuery< K, V >.SearchKey.
SizeContainer WinFormsApp1.Storage< K, V >.SizeContainer()
Публичный геттер для контейнера, содержащего размер хранилища.
References WinFormsApp1.Storage< K, V >._size.
Referenced by WinFormsApp1.HashMap< int, WindowsFormsApp1.Client >::HashMap, WinFormsApp1.Storage< K, V >.Storage.
void WinFormsApp1.DoubleHashStorage< K, V >.Inflate()
Функция, позволяющая увеличить размер хранилища в два раза. Также обновляет положение всех элементов, в соответствии с новыми значениями хэш-функций.
References WinFormsApp1.DoubleHashStorage< K, V >._array, WinFormsApp1.DoubleHashStorage< K, V >._deleted, WinFormsApp1.DoubleHashStorage< K, V >._outsideFunction, WinFormsApp1.DoubleHashStorage< K, V >._size, WinFormsApp1.DoubleHashStorage< K, V >.Add, WinFormsApp1.HashFunction< T >.Hash, WinFormsApp1.DoubleHashStorage< K, V >.ToArray.
Referenced by WinFormsApp1.DoubleHashStorage< K, V >.Add.