WindowsFormsApp1::WaterMarkTextBox
Font WindowsFormsApp1.WaterMarkTextBox.oldFont
Referenced by WindowsFormsApp1.WaterMarkTextBox.EnableWaterMark, WindowsFormsApp1.WaterMarkTextBox.DisbaleWaterMark, WindowsFormsApp1.WaterMarkTextBox.WaterMark_FontChanged.
Boolean WindowsFormsApp1.WaterMarkTextBox.waterMarkTextEnabled
Referenced by WindowsFormsApp1.WaterMarkTextBox.OnPaint, WindowsFormsApp1.WaterMarkTextBox.WaterMark_FontChanged.
Color WindowsFormsApp1.WaterMarkTextBox._waterMarkColor
string WindowsFormsApp1.WaterMarkTextBox._waterMarkText
Color WindowsFormsApp1.WaterMarkTextBox.WaterMarkColor
Referenced by WindowsFormsApp1.GUI.InitializeComponent, WindowsFormsApp1.HashMap1Dialog.InitializeComponent, WindowsFormsApp1.HashMap2Dialog.InitializeComponent, WindowsFormsApp1.Tree1Dialog.InitializeComponent, WindowsFormsApp1.Tree2Dialog.InitializeComponent, WindowsFormsApp1.WaterMarkTextBox.OnPaint.
string WindowsFormsApp1.WaterMarkTextBox.WaterMarkText
Referenced by WindowsFormsApp1.GUI.comboBox1_SelectedIndexChanged, WindowsFormsApp1.GUI.InitializeComponent, WindowsFormsApp1.HashMap1Dialog.InitializeComponent, WindowsFormsApp1.HashMap2Dialog.InitializeComponent, WindowsFormsApp1.Tree1Dialog.InitializeComponent, WindowsFormsApp1.Tree2Dialog.InitializeComponent, WindowsFormsApp1.WaterMarkTextBox.OnPaint.
WindowsFormsApp1.WaterMarkTextBox.WaterMarkTextBox()
References WindowsFormsApp1.WaterMarkTextBox.JoinEvents.
override void WindowsFormsApp1.WaterMarkTextBox.OnCreateControl()
References WindowsFormsApp1.WaterMarkTextBox.WaterMark_Toggel.
override void WindowsFormsApp1.WaterMarkTextBox.OnPaint(PaintEventArgs args)
References WindowsFormsApp1.WaterMarkTextBox.WaterMarkColor, WindowsFormsApp1.WaterMarkTextBox.WaterMarkText, WindowsFormsApp1.WaterMarkTextBox.waterMarkTextEnabled.
void WindowsFormsApp1.WaterMarkTextBox.JoinEvents(Boolean join)
References WindowsFormsApp1.WaterMarkTextBox.WaterMark_FontChanged, WindowsFormsApp1.WaterMarkTextBox.WaterMark_Toggel.
Referenced by WindowsFormsApp1.WaterMarkTextBox.WaterMarkTextBox.
void WindowsFormsApp1.WaterMarkTextBox.WaterMark_Toggel(object sender, EventArgs args)
References WindowsFormsApp1.WaterMarkTextBox.DisbaleWaterMark, WindowsFormsApp1.WaterMarkTextBox.EnableWaterMark.
Referenced by WindowsFormsApp1.WaterMarkTextBox.JoinEvents, WindowsFormsApp1.WaterMarkTextBox.OnCreateControl.
void WindowsFormsApp1.WaterMarkTextBox.EnableWaterMark()
References WindowsFormsApp1.WaterMarkTextBox.oldFont.
Referenced by WindowsFormsApp1.WaterMarkTextBox.WaterMark_Toggel.
void WindowsFormsApp1.WaterMarkTextBox.DisbaleWaterMark()
References WindowsFormsApp1.WaterMarkTextBox.oldFont.
Referenced by WindowsFormsApp1.WaterMarkTextBox.WaterMark_Toggel.
void WindowsFormsApp1.WaterMarkTextBox.WaterMark_FontChanged(object sender, EventArgs args)
References WindowsFormsApp1.WaterMarkTextBox.oldFont, WindowsFormsApp1.WaterMarkTextBox.waterMarkTextEnabled.
Referenced by WindowsFormsApp1.WaterMarkTextBox.JoinEvents.