WindowsFormsApp1::Report::Container
T WindowsFormsApp1.Report< K, V >.Container< T >._element
Данное, хранящееся в контейнере.
Referenced by WindowsFormsApp1.Report< K, V >.Container< V >::Container, WindowsFormsApp1.Report< K, V >.Container< V >::Fill.
Container<T> WindowsFormsApp1.Report< K, V >.Container< T >._next
Следующий элемент списка.
Referenced by WindowsFormsApp1.Report< K, V >.Container< V >::Add, WindowsFormsApp1.Report< K, V >.Container< V >::Size, WindowsFormsApp1.Report< K, V >.Container< V >::Fill.
WindowsFormsApp1.Report< K, V >.Container< T >.Container(T element)
Конструктор для контейнера, хранящего определенный элемент.
element Элемент, хранящийся в контейнере.
void WindowsFormsApp1.Report< K, V >.Container< T >.Add(Container< T > container)
Добавляет контейнер в конец списка.
container Добавляемый контейнер.
Referenced by WindowsFormsApp1.Report< K, V >.Add.
int WindowsFormsApp1.Report< K, V >.Container< T >.Size()
Возвращает количество элементов в списке.
Количество элементов в списке.
Referenced by WindowsFormsApp1.Report< K, V >.Data, WindowsFormsApp1.Report< K, V >.DataSize.
void WindowsFormsApp1.Report< K, V >.Container< T >.Fill(T[] arr, int pos)
Заполняет массив, начиная с указанной позиции, элементами данного списка.
arr Массив для заполнения. pos Позиция для начала заполнения.
Referenced by WindowsFormsApp1.Report< K, V >.Data.