WindowsFormsApp1::GUI
int WindowsFormsApp1.GUI.NumRows1
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.NumRows2
Referenced by WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.NumRows3
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.NumRows4
Referenced by WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.index1
Referenced by WindowsFormsApp1.GUI.dataGridView1_CellClick, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.index2
Referenced by WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.dataGridView3_CellClick, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.index3
Referenced by WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.GUI.dataGridView2_CellClick, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
int WindowsFormsApp1.GUI.index4
Referenced by WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.GUI.dataGridView4_CellClick, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
string WindowsFormsApp1.GUI.state
Referenced by WindowsFormsApp1.GUI.comboBox1_SelectedIndexChanged, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click.
System.ComponentModel.IContainer WindowsFormsApp1.GUI.components
Обязательная переменная конструктора.
Referenced by WindowsFormsApp1.GUI.Dispose.
System.Windows.Forms.MenuStrip WindowsFormsApp1.GUI.menuStrip1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.создатьToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.импортироватьToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.сохранитьToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridView WindowsFormsApp1.GUI.dataGridView1
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click, WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.GUI.label1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.GUI.label2
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.GUI.label3
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.GUI.label4
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridView WindowsFormsApp1.GUI.dataGridView2
Referenced by WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click, WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridView WindowsFormsApp1.GUI.dataGridView3
Referenced by WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click, WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridView WindowsFormsApp1.GUI.dataGridView4
Referenced by WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click, WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button2
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button3
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button4
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button5
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button6
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button7
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button8
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.отчётыToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Label WindowsFormsApp1.GUI.label5
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.Button WindowsFormsApp1.GUI.button9
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ToolStripMenuItem WindowsFormsApp1.GUI.создатьToolStripMenuItem1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Hash
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Номер
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Адрес
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.НазваниеБанка
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Hash1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.НомерКарточки
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Банк
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.ФИО
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Тип
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Отправитель
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Получатель
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.Процент
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.ТипОперации1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.НомерКарточки1
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.НомерБанкомата
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn WindowsFormsApp1.GUI.СуммаОперации
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
WindowsFormsApp1.WaterMarkTextBox WindowsFormsApp1.GUI.waterMarkTextBox1
Referenced by WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.comboBox1_SelectedIndexChanged, WindowsFormsApp1.GUI.InitializeComponent.
System.Windows.Forms.ComboBox WindowsFormsApp1.GUI.comboBox1
Referenced by WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.comboBox1_SelectedIndexChanged, WindowsFormsApp1.GUI.InitializeComponent.
bool WindowsFormsApp1.GUI.stopflag
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.HashMap1Dialog.button2_Click, WindowsFormsApp1.HashMap2Dialog.button2_Click, WindowsFormsApp1.Tree1Dialog.button2_Click, WindowsFormsApp1.Tree2Dialog.button2_Click.
Database WindowsFormsApp1.GUI.myDatabase
Referenced by WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.сохранитьToolStripMenuItem_Click, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click, WindowsFormsApp1.OperationsOfClient.ClientsKey_CellClick, WindowsFormsApp1.OperationsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfMachine.MachinesKey_CellClick, WindowsFormsApp1.PercentsOfOperation.OperationsKey_CellClick.
WindowsFormsApp1.GUI.GUI()
References WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button1_Click(object sender, EventArgs e)
References WindowsFormsApp1.Database.AddMachine, WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.Machine.GetKey, WinFormsApp1.HashFunction< T >.Hash, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.Database.MachinesFunction, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows1, WindowsFormsApp1.GUI.stopflag, WindowsFormsApp1.HashMap1Dialog.waterMarkTextBox1, WindowsFormsApp1.HashMap1Dialog.waterMarkTextBox2, WindowsFormsApp1.HashMap1Dialog.waterMarkTextBox3.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button3_Click(object sender, EventArgs e)
References WindowsFormsApp1.Database.AddClient, WindowsFormsApp1.Database.ClientsFunction, WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.Client.GetKey, WinFormsApp1.HashFunction< T >.Hash, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows2, WindowsFormsApp1.GUI.stopflag, WindowsFormsApp1.HashMap2Dialog.waterMarkTextBox1, WindowsFormsApp1.HashMap2Dialog.waterMarkTextBox2, WindowsFormsApp1.HashMap2Dialog.waterMarkTextBox3.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button2_Click(object sender, EventArgs e)
References WindowsFormsApp1.Database.AddPercent, WindowsFormsApp1.GUI.dataGridView2, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows3, WindowsFormsApp1.GUI.stopflag, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox1, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox2, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox3, WindowsFormsApp1.Tree1Dialog.waterMarkTextBox4.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button4_Click(object sender, EventArgs e)
References WindowsFormsApp1.Database.AddOperation, WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows4, WindowsFormsApp1.GUI.stopflag, WindowsFormsApp1.Tree2Dialog.waterMarkTextBox1, WindowsFormsApp1.Tree2Dialog.waterMarkTextBox2, WindowsFormsApp1.Tree2Dialog.waterMarkTextBox3, WindowsFormsApp1.Tree2Dialog.waterMarkTextBox4.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.dataGridView1_CellClick(object sender, DataGridViewCellEventArgs e)
References WindowsFormsApp1.GUI.index1.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button5_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows1, WindowsFormsApp1.Database.RemoveMachine.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button6_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.GUI.index2, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows2, WindowsFormsApp1.Database.RemoveClient.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button7_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.dataGridView2, WindowsFormsApp1.GUI.index3, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows3, WindowsFormsApp1.Database.RemovePercent.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button8_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.GUI.index4, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows4, WindowsFormsApp1.Database.RemoveOperation.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.dataGridView3_CellClick(object sender, DataGridViewCellEventArgs e)
References WindowsFormsApp1.GUI.index2.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.dataGridView2_CellClick(object sender, DataGridViewCellEventArgs e)
References WindowsFormsApp1.GUI.index3.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.dataGridView4_CellClick(object sender, DataGridViewCellEventArgs e)
References WindowsFormsApp1.GUI.index4.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.button9_Click(object sender, EventArgs e)
References WindowsFormsApp1.ClientFound.ClientResults, WindowsFormsApp1.GUI.comboBox1, WindowsFormsApp1.SearchQuery< T >.Counter, WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.GUI.dataGridView2, WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.Database.FindClient, WindowsFormsApp1.Database.FindMachine, WindowsFormsApp1.Database.FindOperation, WindowsFormsApp1.Database.FindPercent, WindowsFormsApp1.SearchQuery< T >.Found, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.operationFound.label1, WindowsFormsApp1.ClientFound.label1, WindowsFormsApp1.MachineFound.label3, WindowsFormsApp1.percentFound.label3, WindowsFormsApp1.MachineFound.MachineResults, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.operationFound.operationResults, WindowsFormsApp1.percentFound.percentResults, WindowsFormsApp1.GUI.waterMarkTextBox1.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.comboBox1_SelectedIndexChanged(object sender, EventArgs e)
References WindowsFormsApp1.GUI.comboBox1, WindowsFormsApp1.GUI.state, WindowsFormsApp1.WaterMarkTextBox.WaterMarkText, WindowsFormsApp1.GUI.waterMarkTextBox1.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click(object sender, EventArgs e)
References WindowsFormsApp1.Operation.CardNumber, WindowsFormsApp1.Database.ClientOperationReport, WindowsFormsApp1.Report< K, V >.Data, WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.Report< K, V >.DataSize, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.Operation.MachineNumber, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Operation.Sum.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click(object sender, EventArgs e)
References WindowsFormsApp1.Operation.CardNumber, WindowsFormsApp1.Report< K, V >.Data, WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.Report< K, V >.DataSize, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.Operation.MachineNumber, WindowsFormsApp1.Database.MachineOperationReport, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Operation.Sum.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click(object sender, EventArgs e)
References WindowsFormsApp1.Report< K, V >.Data, WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.Report< K, V >.DataSize, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.Percent.OperationName, WindowsFormsApp1.Database.OperationPercentReport, WindowsFormsApp1.Percent.Percent1, WindowsFormsApp1.Percent.ReceiverBank, WindowsFormsApp1.Percent.SenderBank.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click(object sender, EventArgs e)
References WindowsFormsApp1.Report< K, V >.Data, WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.Report< K, V >.DataSize, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.Database.MachinePercentReport, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.Percent.OperationName, WindowsFormsApp1.Percent.Percent1, WindowsFormsApp1.Percent.ReceiverBank, WindowsFormsApp1.Percent.SenderBank.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.сохранитьToolStripMenuItem_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.Database.Save.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click(object sender, EventArgs e)
References WindowsFormsApp1.Machine.Address, WindowsFormsApp1.Client.BankName, WindowsFormsApp1.Machine.BankName, WindowsFormsApp1.Client.CardNumber, WindowsFormsApp1.Operation.CardNumber, WindowsFormsApp1.Database.ClientArray, WindowsFormsApp1.Database.ClientsFunction, WindowsFormsApp1.Database.ClientSize, WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.GUI.dataGridView2, WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.Database.GetInstance, WinFormsApp1.HashFunction< T >.Hash, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.GUI.index2, WindowsFormsApp1.GUI.index3, WindowsFormsApp1.GUI.index4, WindowsFormsApp1.ErrorForm.label1, WindowsFormsApp1.Database.MachineArray, WindowsFormsApp1.Machine.MachineNumber, WindowsFormsApp1.Operation.MachineNumber, WindowsFormsApp1.Database.MachinesFunction, WindowsFormsApp1.Database.MachineSize, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.Client.Name, WindowsFormsApp1.GUI.NumRows1, WindowsFormsApp1.GUI.NumRows2, WindowsFormsApp1.GUI.NumRows3, WindowsFormsApp1.GUI.NumRows4, WindowsFormsApp1.Database.OperationArray, WindowsFormsApp1.Operation.OperationName, WindowsFormsApp1.Percent.OperationName, WindowsFormsApp1.Database.OperationSize, WindowsFormsApp1.Percent.Percent1, WindowsFormsApp1.Database.PercentArray, WindowsFormsApp1.Database.PercentSize, WindowsFormsApp1.Percent.ReceiverBank, WindowsFormsApp1.Percent.SenderBank, WindowsFormsApp1.GUI.state, WindowsFormsApp1.Operation.Sum.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click(object sender, EventArgs e)
References WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.GUI.dataGridView2, WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.Database.GetNewInstance, WindowsFormsApp1.GUI.index1, WindowsFormsApp1.GUI.index2, WindowsFormsApp1.GUI.index3, WindowsFormsApp1.GUI.index4, WindowsFormsApp1.GUI.myDatabase, WindowsFormsApp1.GUI.NumRows1, WindowsFormsApp1.GUI.NumRows2, WindowsFormsApp1.GUI.NumRows3, WindowsFormsApp1.GUI.NumRows4, WindowsFormsApp1.GUI.state.
Referenced by WindowsFormsApp1.GUI.InitializeComponent.
void WindowsFormsApp1.GUI.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References WindowsFormsApp1.GUI.button1, WindowsFormsApp1.GUI.button1_Click, WindowsFormsApp1.GUI.button2, WindowsFormsApp1.GUI.button2_Click, WindowsFormsApp1.GUI.button3, WindowsFormsApp1.GUI.button3_Click, WindowsFormsApp1.GUI.button4, WindowsFormsApp1.GUI.button4_Click, WindowsFormsApp1.GUI.button5, WindowsFormsApp1.GUI.button5_Click, WindowsFormsApp1.GUI.button6, WindowsFormsApp1.GUI.button6_Click, WindowsFormsApp1.GUI.button7, WindowsFormsApp1.GUI.button7_Click, WindowsFormsApp1.GUI.button8, WindowsFormsApp1.GUI.button8_Click, WindowsFormsApp1.GUI.button9, WindowsFormsApp1.GUI.button9_Click, WindowsFormsApp1.GUI.comboBox1, WindowsFormsApp1.GUI.comboBox1_SelectedIndexChanged, WindowsFormsApp1.GUI.dataGridView1, WindowsFormsApp1.GUI.dataGridView1_CellClick, WindowsFormsApp1.GUI.dataGridView2, WindowsFormsApp1.GUI.dataGridView2_CellClick, WindowsFormsApp1.GUI.dataGridView3, WindowsFormsApp1.GUI.dataGridView3_CellClick, WindowsFormsApp1.GUI.dataGridView4, WindowsFormsApp1.GUI.dataGridView4_CellClick, WindowsFormsApp1.GUI.Hash, WindowsFormsApp1.GUI.Hash1, WindowsFormsApp1.GUI.label1, WindowsFormsApp1.GUI.label2, WindowsFormsApp1.GUI.label3, WindowsFormsApp1.GUI.label4, WindowsFormsApp1.GUI.label5, WindowsFormsApp1.GUI.menuStrip1, WindowsFormsApp1.WaterMarkTextBox.WaterMarkColor, WindowsFormsApp1.WaterMarkTextBox.WaterMarkText, WindowsFormsApp1.GUI.waterMarkTextBox1, WindowsFormsApp1.GUI.Адрес, WindowsFormsApp1.GUI.Банк, WindowsFormsApp1.GUI.НазваниеБанка, WindowsFormsApp1.GUI.Номер, WindowsFormsApp1.GUI.НомерБанкомата, WindowsFormsApp1.GUI.НомерКарточки, WindowsFormsApp1.GUI.НомерКарточки1, WindowsFormsApp1.GUI.Отправитель, WindowsFormsApp1.GUI.Получатель, WindowsFormsApp1.GUI.Процент, WindowsFormsApp1.GUI.СуммаОперации, WindowsFormsApp1.GUI.Тип, WindowsFormsApp1.GUI.ТипОперации1, WindowsFormsApp1.GUI.ФИО, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem, WindowsFormsApp1.GUI.импортироватьToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem, WindowsFormsApp1.GUI.операцииБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem, WindowsFormsApp1.GUI.операцииПоКлиентуToolStripMenuItem_Click, WindowsFormsApp1.GUI.отчётыToolStripMenuItem, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem, WindowsFormsApp1.GUI.процентыБанкоматаToolStripMenuItem_Click, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem, WindowsFormsApp1.GUI.процентыОперацийToolStripMenuItem_Click, WindowsFormsApp1.GUI.создатьToolStripMenuItem, WindowsFormsApp1.GUI.создатьToolStripMenuItem1, WindowsFormsApp1.GUI.создатьToolStripMenuItem1_Click, WindowsFormsApp1.GUI.сохранитьToolStripMenuItem, WindowsFormsApp1.GUI.сохранитьToolStripMenuItem_Click.
Referenced by WindowsFormsApp1.GUI.GUI.
override void WindowsFormsApp1.GUI.Dispose(bool disposing)
Освободить все используемые ресурсы.
disposing истинно, если управляемый ресурс должен быть удален; иначе ложно.
References WindowsFormsApp1.GUI.components.